In [1]:
# Import relevant libraries

In [2]:
import pandas as pd
import plotly.plotly as py
import plotly.graph_objs as go
import cufflinks as cf
#Allows the ability to produce plots in Jupyter Notebook
from plotly.offline import init_notebook_mode,iplot,plot
import requests
import json
import prettytable

In [3]:
#Confirms the connection between plotly and Jupyter Notebook
init_notebook_mode(connected=True)

In [4]:
# Import quandl library
# Enter authentication key
# enter date of creation of api version library

In [5]:
import quandl
quandl.ApiConfig.api_key = 'Mm_qHSXMsN3XriByiv9P'
quandl.ApiConfig.api_version = '2015-04-09'

In [6]:
# create a data frame with the Consumer Price Index information collected from the YALE/CPIQ table, using my authntication token
# create a data frame with the Consumer Price Index information collected from the YALE/CPIQ table, using my authntication token from 
# https://www.quandl.com/data/YALE/CPIQ-Historical-Housing-Market-Data-Consumer-Price-Index-Quarterly

In [7]:
#Fetching the data that is equivelant to the ZILL codes by using my api_key token
Louisiana = quandl.get("ZILL/S00025_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Rhode_Island = quandl.get("ZILL/S00041_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Alaska = quandl.get("ZILL/S00045_A", authtoken="Mm_qHSXMsN3XriByiv9P")

In [8]:
Ohio = quandl.get("ZILL/S00007_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Vermont = quandl.get("ZILL/S00047_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Indiana = quandl.get("ZILL/S00015_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Georgia = quandl.get("ZILL/S00009_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Tennessee = quandl.get("ZILL/S00017_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Wisconsin = quandl.get("ZILL/S00020_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Massachusetts = quandl.get("ZILL/S00014_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Kentucky = quandl.get("ZILL/S00026_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Connecticut = quandl.get("ZILL/S00029_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Oregon = quandl.get("ZILL/S00027_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Mississippi = quandl.get("ZILL/S00031_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Montana = quandl.get("ZILL/S00042_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Maine = quandl.get("ZILL/S00051_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Iowa = quandl.get("ZILL/S00030_A", authtoken="Mm_qHSXMsN3XriByiv9P")

In [9]:
New_Jersey = quandl.get("ZILL/S00011_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Illinois = quandl.get("ZILL/S00005_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Missouri = quandl.get("ZILL/S00018_A", authtoken="Mm_qHSXMsN3XriByiv9P")
New_York = quandl.get("ZILL/S00003_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Arizona = quandl.get("ZILL/S00016_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Pennsylvania = quandl.get("ZILL/S00006_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Virginia = quandl.get("ZILL/S00012_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Texas = quandl.get("ZILL/S00002_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Florida = quandl.get("ZILL/S00004_A", authtoken="Mm_qHSXMsN3XriByiv9P")
North_Carolina = quandl.get("ZILL/S00010_A", authtoken="Mm_qHSXMsN3XriByiv9P")
California = quandl.get("ZILL/S00001_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Michigan = quandl.get("ZILL/S00008_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Maryland = quandl.get("ZILL/S00019_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Washington = quandl.get("ZILL/S00013_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Minnesota = quandl.get("ZILL/S00021_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Alabama = quandl.get("ZILL/S00023_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Oklahoma = quandl.get("ZILL/S00028_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Arkansas = quandl.get("ZILL/S00032_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Utah = quandl.get("ZILL/S00033_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Nevada = quandl.get("ZILL/S00034_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Nebraska = quandl.get("ZILL/S00037_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Idaho = quandl.get("ZILL/S00038_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Kansas = quandl.get("ZILL/S00049_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Wyoming = quandl.get("ZILL/S00050_A", authtoken="Mm_qHSXMsN3XriByiv9P")
West_Virginia = quandl.get("ZILL/S00036_A", authtoken="Mm_qHSXMsN3XriByiv9P")
New_Mexico = quandl.get("ZILL/S00035_A", authtoken="Mm_qHSXMsN3XriByiv9P")
New_Hampshire = quandl.get("ZILL/S00040_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Delaware = quandl.get("ZILL/S00043_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Hawaii = quandl.get("ZILL/S00039_A", authtoken="Mm_qHSXMsN3XriByiv9P")
North_Dakota = quandl.get("ZILL/S00046_A", authtoken="Mm_qHSXMsN3XriByiv9P")
District_of_Columbia = quandl.get("ZILL/S00048_A", authtoken="Mm_qHSXMsN3XriByiv9P")
Colorado = quandl.get("ZILL/S00022_A", authtoken="Mm_qHSXMsN3XriByiv9P")
South_Dakota = quandl.get("ZILL/S00044_A", authtoken="Mm_qHSXMsN3XriByiv9P")
South_Carolina = quandl.get("ZILL/S00024_A", authtoken="Mm_qHSXMsN3XriByiv9P")

In [10]:
#Checking the first 5 rows of each data frame created above
Arizona.head()

               Value
Date
1996-04-30  102900.0
1996-05-31  103300.0
1996-06-30  103600.0
1996-07-31  103800.0
1996-08-31  103900.0

In [11]:
#Resetting the index of each data frame 
AL = Alabama.reset_index(drop=False)
AK = Alaska.reset_index(drop=False)
AZ = Arizona.reset_index(drop=False)
AR = Arkansas.reset_index(drop=False)
CA = California.reset_index(drop=False)
CO = Colorado.reset_index(drop=False)
CT = Connecticut.reset_index(drop=False)
DC = District_of_Columbia.reset_index(drop=False)
DE = Delaware.reset_index(drop=False)
FL = Florida.reset_index(drop=False)
GA = Georgia.reset_index(drop=False)
HI = Hawaii.reset_index(drop=False)
ID = Idaho.reset_index(drop=False)
IL = Illinois.reset_index(drop=False)
IN = Indiana.reset_index(drop=False)
IA = Iowa.reset_index(drop=False)
KS = Kansas.reset_index(drop=False)
KY = Kentucky.reset_index(drop=False)
LA = Louisiana.reset_index(drop=False)
ME = Maine.reset_index(drop=False)
MD = Maryland.reset_index(drop=False)
MA = Massachusetts.reset_index(drop=False)
MI = Michigan.reset_index(drop=False)
MN = Minnesota.reset_index(drop=False)
MS = Mississippi.reset_index(drop=False)
MO = Missouri.reset_index(drop=False)
MT = Montana.reset_index(drop=False)
NE = Nebraska.reset_index(drop=False)
NV = Nevada.reset_index(drop=False)
NH = New_Hampshire.reset_index(drop=False)
NJ = New_Jersey.reset_index(drop=False)
NM = New_Mexico.reset_index(drop=False)
NY = New_York.reset_index(drop=False)
NC = North_Carolina.reset_index(drop=False)
ND = North_Dakota.reset_index(drop=False)
OH = Ohio.reset_index(drop=False)
OK = Oklahoma.reset_index(drop=False)
OR = Oregon.reset_index(drop=False)
PA = Pennsylvania.reset_index(drop=False)
RI = Rhode_Island.reset_index(drop=False)
SC = South_Carolina.reset_index(drop=False)
SD = South_Dakota.reset_index(drop=False)
TN = Tennessee.reset_index(drop=False)
TX = Texas.reset_index(drop=False)
UT = Utah.reset_index(drop=False)
VT = Vermont.reset_index(drop=False)
VA = Virginia.reset_index(drop=False)
WA = Washington.reset_index(drop=False)
WV = West_Virginia.reset_index(drop=False)
WI = Wisconsin.reset_index(drop=False)
WY = Wyoming.reset_index(drop=False)
#newdf = Arizona[(Arizona['Date']>1999-12-31)]
#keep = [1999-12-31]
#keep = Arizona[Arizona['Date'].isin(keep)]

In [12]:
#Viewing the frist 5 rows of AL
AL.head()

        Date    Value
0 1996-04-30  83500.0
1 1996-05-31  83400.0
2 1996-06-30  83700.0
3 1996-07-31  83800.0
4 1996-08-31  83700.0

In [14]:
#Filtering through each data frame and only selecting the rows in which the date is no earlier that 31st Deember 2009
AL = AL[(AL['Date']>'2005-12-31')]
AK = AK[(AK['Date']>'2005-12-31')]
AZ = AZ[(AZ['Date']>'2005-12-31')]
AR = AR[(AR['Date']>'2005-12-31')]
CA = CA[(CA['Date']>'2005-12-31')]
CO = CO[(CO['Date']>'2005-12-31')]
CT = CT[(CT['Date']>'2005-12-31')]
DC = DC[(DC['Date']>'2005-12-31')]
DE = DE[(DE['Date']>'2005-12-31')]
FL = FL[(FL['Date']>'2005-12-31')]
GA = GA[(GA['Date']>'2005-12-31')]
HI = HI[(HI['Date']>'2005-12-31')]
ID = ID[(ID['Date']>'2005-12-31')]
IL = IL[(IL['Date']>'2005-12-31')]
IN = IN[(IN['Date']>'2005-12-31')]
IA = IA[(IA['Date']>'2005-12-31')]
KS = KS[(KS['Date']>'2005-12-31')]
KY = KY[(KY['Date']>'2005-12-31')]
LA = LA[(LA['Date']>'2005-12-31')]
ME = ME[(ME['Date']>'2005-12-31')]
MD = MD[(MD['Date']>'2005-12-31')]
MA = MA[(MA['Date']>'2005-12-31')]
MI = MI[(MI['Date']>'2005-12-31')]
MN = MN[(MN['Date']>'2005-12-31')]
MS = MS[(MS['Date']>'2005-12-31')]
MO = MO[(MO['Date']>'2005-12-31')]
MT = MT[(MT['Date']>'2005-12-31')]
NE = NE[(NE['Date']>'2005-12-31')]
NV = NV[(NV['Date']>'2005-12-31')]
NH = NH[(NH['Date']>'2005-12-31')]
NJ = NJ[(NJ['Date']>'2005-12-31')]
NM = NM[(NM['Date']>'2005-12-31')]
NY = NY[(NY['Date']>'2005-12-31')]
NC = NC[(NC['Date']>'2005-12-31')]
ND = ND[(ND['Date']>'2005-12-31')]
OH = OH[(OH['Date']>'2005-12-31')]
OK = OK[(OK['Date']>'2005-12-31')]
OR = OR[(OR['Date']>'2005-12-31')]
PA = PA[(PA['Date']>'2005-12-31')]
RI = RI[(RI['Date']>'2005-12-31')]
SC = SC[(SC['Date']>'2005-12-31')]
SD = SD[(SD['Date']>'2005-12-31')]
TN = TN[(TN['Date']>'2005-12-31')]
TX = TX[(TX['Date']>'2005-12-31')]
UT = UT[(UT['Date']>'2005-12-31')]
VT = VT[(VT['Date']>'2005-12-31')]
VA = VA[(VA['Date']>'2005-12-31')]
WA = WA[(WA['Date']>'2005-12-31')]
WV = WV[(WV['Date']>'2005-12-31')]
WI = WI[(WI['Date']>'2005-12-31')]
WY = WY[(WY['Date']>'2005-12-31')]

In [15]:
#Viewing some of the data frames
AL,AK,AZ,AR,CA,CO,CT,DE,DC,FL,GA,HI,ID,IL,IN,IA,KS,KY,LA,ME,MD,MA,MI

(          Date     Value
 117 2006-01-31  124000.0
 118 2006-02-28  124700.0
 119 2006-03-31  125200.0
 120 2006-04-30  125600.0
 121 2006-05-31  126100.0
 122 2006-06-30  126600.0
 123 2006-07-31  127200.0
 124 2006-08-31  127600.0
 125 2006-09-30  127700.0
 126 2006-10-31  127800.0
 127 2006-11-30  128300.0
 128 2006-12-31  129100.0
 129 2007-01-31  129400.0
 130 2007-02-28  129300.0
 131 2007-03-31  129300.0
 132 2007-04-30  129300.0
 133 2007-05-31  129200.0
 134 2007-06-30  129300.0
 135 2007-07-31  129700.0
 136 2007-08-31  129900.0
 137 2007-09-30  130000.0
 138 2007-10-31  130000.0
 139 2007-11-30  129500.0
 140 2007-12-31  128400.0
 141 2008-01-31  127400.0
 142 2008-02-29  126800.0
 143 2008-03-31  126500.0
 144 2008-04-30  126500.0
 145 2008-05-31  126700.0
 146 2008-06-30  127300.0
 ..         ...       ...
 220 2014-08-31  121100.0
 221 2014-09-30  121400.0
 222 2014-10-31  121800.0
 223 2014-11-30  122000.0
 224 2014-12-31  121800.0
 225 2015-01-31  121400.0
 226 2015-02-28  120600.0
 227 2015-03-31  120600.0
 228 2015-04-30  120600.0
 229 2015-05-31  121300.0
 230 2015-06-30  122000.0
 231 2015-07-31  121700.0
 232 2015-08-31  122300.0
 233 2015-09-30  122800.0
 234 2015-10-31  122200.0
 235 2015-11-30  122600.0
 236 2015-12-31  122700.0
 237 2016-01-31  123100.0
 238 2016-02-29  123100.0
 239 2016-03-31  122900.0
 240 2016-04-30  123300.0
 241 2016-05-31  122900.0
 242 2016-06-30  122700.0
 243 2016-07-31  122300.0
 244 2016-08-31  122300.0
 245 2016-09-30  122500.0
 246 2016-10-31  122800.0
 247 2016-11-30  123200.0
 248 2016-12-31  123800.0
 249 2017-01-31  124600.0

 [133 rows x 2 columns],           Date     Value
 90  2006-01-31  235100.0
 91  2006-02-28  237100.0
 92  2006-03-31  238700.0
 93  2006-04-30  239000.0
 94  2006-05-31  238500.0
 95  2006-06-30  237700.0
 96  2006-07-31  236100.0
 97  2006-08-31  234700.0
 98  2006-09-30  235300.0
 99  2006-10-31  237200.0
 100 2006-11-30  239000.0
 101 2006-12-31  243500.0
 102 2007-01-31  249500.0
 103 2007-02-28  255300.0
 104 2007-03-31  258800.0
 105 2007-04-30  261500.0
 106 2007-05-31  261900.0
 107 2007-06-30  262700.0
 108 2007-07-31  264000.0
 109 2007-08-31  265600.0
 110 2007-09-30  265700.0
 111 2007-10-31  265500.0
 112 2007-11-30  264700.0
 113 2007-12-31  265900.0
 114 2008-01-31  267800.0
 115 2008-02-29  268200.0
 116 2008-03-31  267200.0
 117 2008-04-30  268400.0
 118 2008-05-31  269900.0
 119 2008-06-30  271300.0
 ..         ...       ...
 193 2014-08-31  255600.0
 194 2014-09-30  254400.0
 195 2014-10-31  253600.0
 196 2014-11-30  253300.0
 197 2014-12-31  254900.0
 198 2015-01-31  257200.0
 199 2015-02-28  258000.0
 200 2015-03-31  257300.0
 201 2015-04-30  257200.0
 202 2015-05-31  258100.0
 203 2015-06-30  259500.0
 204 2015-07-31  260500.0
 205 2015-08-31  262000.0
 206 2015-09-30  262200.0
 207 2015-10-31  262400.0
 208 2015-11-30  262700.0
 209 2015-12-31  264100.0
 210 2016-01-31  265400.0
 211 2016-02-29  266200.0
 212 2016-03-31  267500.0
 213 2016-04-30  268600.0
 214 2016-05-31  266500.0
 215 2016-06-30  266400.0
 216 2016-07-31  266500.0
 217 2016-08-31  266800.0
 218 2016-09-30  265300.0
 219 2016-10-31  265300.0
 220 2016-11-30  265700.0
 221 2016-12-31  266300.0
 222 2017-01-31  267000.0

 [133 rows x 2 columns],           Date     Value
 117 2006-01-31  259900.0
 118 2006-02-28  261600.0
 119 2006-03-31  262900.0
 120 2006-04-30  263500.0
 121 2006-05-31  263500.0
 122 2006-06-30  263000.0
 123 2006-07-31  262100.0
 124 2006-08-31  260900.0
 125 2006-09-30  259400.0
 126 2006-10-31  257700.0
 127 2006-11-30  256100.0
 128 2006-12-31  254300.0
 129 2007-01-31  252300.0
 130 2007-02-28  250300.0
 131 2007-03-31  248400.0
 132 2007-04-30  246700.0
 133 2007-05-31  245000.0
 134 2007-06-30  243300.0
 135 2007-07-31  241700.0
 136 2007-08-31  240200.0
 137 2007-09-30  238600.0
 138 2007-10-31  236900.0
 139 2007-11-30  234900.0
 140 2007-12-31  232200.0
 141 2008-01-31  228500.0
 142 2008-02-29  224500.0
 143 2008-03-31  220500.0
 144 2008-04-30  216700.0
 145 2008-05-31  213300.0
 146 2008-06-30  209700.0
 ..         ...       ...
 220 2014-08-31  185000.0
 221 2014-09-30  186500.0
 222 2014-10-31  188100.0
 223 2014-11-30  189700.0
 224 2014-12-31  191200.0
 225 2015-01-31  192100.0
 226 2015-02-28  192500.0
 227 2015-03-31  191800.0
 228 2015-04-30  191300.0
 229 2015-05-31  191300.0
 230 2015-06-30  192300.0
 231 2015-07-31  193900.0
 232 2015-08-31  196400.0
 233 2015-09-30  198600.0
 234 2015-10-31  199900.0
 235 2015-11-30  202600.0
 236 2015-12-31  203600.0
 237 2016-01-31  204600.0
 238 2016-02-29  205000.0
 239 2016-03-31  206100.0
 240 2016-04-30  207000.0
 241 2016-05-31  207300.0
 242 2016-06-30  208000.0
 243 2016-07-31  208800.0
 244 2016-08-31  210200.0
 245 2016-09-30  213200.0
 246 2016-10-31  214700.0
 247 2016-11-30  216200.0
 248 2016-12-31  217900.0
 249 2017-01-31  219000.0

 [133 rows x 2 columns],           Date     Value
 117 2006-01-31   93200.0
 118 2006-02-28   93600.0
 119 2006-03-31   94200.0
 120 2006-04-30   94500.0
 121 2006-05-31   94800.0
 122 2006-06-30   94800.0
 123 2006-07-31   95100.0
 124 2006-08-31   95700.0
 125 2006-09-30   95800.0
 126 2006-10-31   95300.0
 127 2006-11-30   95400.0
 128 2006-12-31   95900.0
 129 2007-01-31   96300.0
 130 2007-02-28   96600.0
 131 2007-03-31   97100.0
 132 2007-04-30   97500.0
 133 2007-05-31   97700.0
 134 2007-06-30   97900.0
 135 2007-07-31   98300.0
 136 2007-08-31   98500.0
 137 2007-09-30   98700.0
 138 2007-10-31   99300.0
 139 2007-11-30   99900.0
 140 2007-12-31   99600.0
 141 2008-01-31   99300.0
 142 2008-02-29   99200.0
 143 2008-03-31   99400.0
 144 2008-04-30   99400.0
 145 2008-05-31   99100.0
 146 2008-06-30   98800.0
 ..         ...       ...
 220 2014-08-31  110900.0
 221 2014-09-30  111800.0
 222 2014-10-31  112700.0
 223 2014-11-30  113600.0
 224 2014-12-31  114500.0
 225 2015-01-31  115100.0
 226 2015-02-28  114800.0
 227 2015-03-31  114000.0
 228 2015-04-30  114200.0
 229 2015-05-31  114500.0
 230 2015-06-30  114000.0
 231 2015-07-31  113800.0
 232 2015-08-31  113500.0
 233 2015-09-30  114400.0
 234 2015-10-31  114000.0
 235 2015-11-30  114800.0
 236 2015-12-31  114900.0
 237 2016-01-31  115200.0
 238 2016-02-29  115300.0
 239 2016-03-31  115400.0
 240 2016-04-30  116500.0
 241 2016-05-31  114700.0
 242 2016-06-30  114800.0
 243 2016-07-31  114400.0
 244 2016-08-31  115000.0
 245 2016-09-30  114100.0
 246 2016-10-31  114900.0
 247 2016-11-30  115300.0
 248 2016-12-31  116100.0
 249 2017-01-31  116700.0

 [133 rows x 2 columns],           Date     Value
 117 2006-01-31  534500.0
 118 2006-02-28  536100.0
 119 2006-03-31  537500.0
 120 2006-04-30  538300.0
 121 2006-05-31  538300.0
 122 2006-06-30  537700.0
 123 2006-07-31  536600.0
 124 2006-08-31  534800.0
 125 2006-09-30  532400.0
 126 2006-10-31  529600.0
 127 2006-11-30  527000.0
 128 2006-12-31  523900.0
 129 2007-01-31  521000.0
 130 2007-02-28  518700.0
 131 2007-03-31  516700.0
 132 2007-04-30  513900.0
 133 2007-05-31  510500.0
 134 2007-06-30  506100.0
 135 2007-07-31  501200.0
 136 2007-08-31  496200.0
 137 2007-09-30  490900.0
 138 2007-10-31  485400.0
 139 2007-11-30  479300.0
 140 2007-12-31  471900.0
 141 2008-01-31  463300.0
 142 2008-02-29  454100.0
 143 2008-03-31  443900.0
 144 2008-04-30  433300.0
 145 2008-05-31  423000.0
 146 2008-06-30  413200.0
 ..         ...       ...
 220 2014-08-31  427400.0
 221 2014-09-30  429400.0
 222 2014-10-31  431500.0
 223 2014-11-30  433500.0
 224 2014-12-31  435300.0
 225 2015-01-31  436600.0
 226 2015-02-28  439500.0
 227 2015-03-31  440000.0
 228 2015-04-30  440700.0
 229 2015-05-31  441800.0
 230 2015-06-30  443200.0
 231 2015-07-31  445500.0
 232 2015-08-31  448400.0
 233 2015-09-30  447500.0
 234 2015-10-31  449200.0
 235 2015-11-30  452300.0
 236 2015-12-31  454600.0
 237 2016-01-31  456800.0
 238 2016-02-29  458500.0
 239 2016-03-31  462100.0
 240 2016-04-30  463600.0
 241 2016-05-31  464200.0
 242 2016-06-30  466300.0
 243 2016-07-31  467000.0
 244 2016-08-31  469500.0
 245 2016-09-30  476700.0
 246 2016-10-31  479700.0
 247 2016-11-30  483200.0
 248 2016-12-31  485900.0
 249 2017-01-31  487700.0

 [133 rows x 2 columns],           Date     Value
 117 2006-01-31  222500.0
 118 2006-02-28  223300.0
 119 2006-03-31  223400.0
 120 2006-04-30  223600.0
 121 2006-05-31  223700.0
 122 2006-06-30  223500.0
 123 2006-07-31  223800.0
 124 2006-08-31  224400.0
 125 2006-09-30  224700.0
 126 2006-10-31  225300.0
 127 2006-11-30  226300.0
 128 2006-12-31  227100.0
 129 2007-01-31  226900.0
 130 2007-02-28  226300.0
 131 2007-03-31  226100.0
 132 2007-04-30  226000.0
 133 2007-05-31  226200.0
 134 2007-06-30  226900.0
 135 2007-07-31  227500.0
 136 2007-08-31  226900.0
 137 2007-09-30  226900.0
 138 2007-10-31  227100.0
 139 2007-11-30  226700.0
 140 2007-12-31  224800.0
 141 2008-01-31  222300.0
 142 2008-02-29  220000.0
 143 2008-03-31  219100.0
 144 2008-04-30  218600.0
 145 2008-05-31  218600.0
 146 2008-06-30  218800.0
 ..         ...       ...
 220 2014-08-31  249100.0
 221 2014-09-30  251400.0
 222 2014-10-31  254000.0
 223 2014-11-30  257000.0
 224 2014-12-31  260500.0
 225 2015-01-31  263200.0
 226 2015-02-28  265700.0
 227 2015-03-31  267100.0
 228 2015-04-30  268700.0
 229 2015-05-31  271300.0
 230 2015-06-30  274400.0
 231 2015-07-31  277300.0
 232 2015-08-31  279700.0
 233 2015-09-30  282200.0
 234 2015-10-31  284000.0
 235 2015-11-30  286500.0
 236 2015-12-31  290100.0
 237 2016-01-31  292500.0
 238 2016-02-29  294200.0
 239 2016-03-31  298500.0
 240 2016-04-30  302200.0
 241 2016-05-31  301200.0
 242 2016-06-30  303600.0
 243 2016-07-31  305300.0
 244 2016-08-31  308000.0
 245 2016-09-30  313700.0
 246 2016-10-31  316200.0
 247 2016-11-30  318700.0
 248 2016-12-31  320900.0
 249 2017-01-31  322300.0

 [133 rows x 2 columns],           Date     Value
 117 2006-01-31  294300.0
 118 2006-02-28  294900.0
 119 2006-03-31  295400.0
 120 2006-04-30  296000.0
 121 2006-05-31  296100.0
 122 2006-06-30  296100.0
 123 2006-07-31  295800.0
 124 2006-08-31  295400.0
 125 2006-09-30  294900.0
 126 2006-10-31  294700.0
 127 2006-11-30  294300.0
 128 2006-12-31  293800.0
 129 2007-01-31  293500.0
 130 2007-02-28  293600.0
 131 2007-03-31  293800.0
 132 2007-04-30  293900.0
 133 2007-05-31  293400.0
 134 2007-06-30  292400.0
 135 2007-07-31  291400.0
 136 2007-08-31  290500.0
 137 2007-09-30  289500.0
 138 2007-10-31  288400.0
 139 2007-11-30  287500.0
 140 2007-12-31  286100.0
 141 2008-01-31  284300.0
 142 2008-02-29  282500.0
 143 2008-03-31  280900.0
 144 2008-04-30  279500.0
 145 2008-05-31  278100.0
 146 2008-06-30  276800.0
 ..         ...       ...
 220 2014-08-31  240600.0
 221 2014-09-30  240200.0
 222 2014-10-31  239900.0
 223 2014-11-30  239700.0
 224 2014-12-31  239600.0
 225 2015-01-31  239500.0
 226 2015-02-28  237100.0
 227 2015-03-31  239800.0
 228 2015-04-30  236500.0
 229 2015-05-31  236800.0
 230 2015-06-30  237300.0
 231 2015-07-31  237600.0
 232 2015-08-31  237800.0
 233 2015-09-30  238500.0
 234 2015-10-31  238000.0
 235 2015-11-30  237200.0
 236 2015-12-31  237400.0
 237 2016-01-31  237700.0
 238 2016-02-29  237900.0
 239 2016-03-31  238600.0
 240 2016-04-30  236200.0
 241 2016-05-31  238900.0
 242 2016-06-30  239300.0
 243 2016-07-31  239700.0
 244 2016-08-31  240500.0
 245 2016-09-30  241500.0
 246 2016-10-31  242300.0
 247 2016-11-30  242900.0
 248 2016-12-31  243100.0
 249 2017-01-31  243300.0

 [133 rows x 2 columns],           Date     Value
 117 2006-01-31  225000.0
 118 2006-02-28  226100.0
 119 2006-03-31  227200.0
 120 2006-04-30  228000.0
 121 2006-05-31  228500.0
 122 2006-06-30  229200.0
 123 2006-07-31  230000.0
 124 2006-08-31  230400.0
 125 2006-09-30  230600.0
 126 2006-10-31  231100.0
 127 2006-11-30  232000.0
 128 2006-12-31  232600.0
 129 2007-01-31  232800.0
 130 2007-02-28  232600.0
 131 2007-03-31  232900.0
 132 2007-04-30  233200.0
 133 2007-05-31  233100.0
 134 2007-06-30  232500.0
 135 2007-07-31  232300.0
 136 2007-08-31  232000.0
 137 2007-09-30  231300.0
 138 2007-10-31  230500.0
 139 2007-11-30  229800.0
 140 2007-12-31  228900.0
 141 2008-01-31  227900.0
 142 2008-02-29  226800.0
 143 2008-03-31  225400.0
 144 2008-04-30  223800.0
 145 2008-05-31  222300.0
 146 2008-06-30  221000.0
 ..         ...       ...
 220 2014-08-31  202700.0
 221 2014-09-30  203700.0
 222 2014-10-31  204800.0
 223 2014-11-30  205400.0
 224 2014-12-31  205200.0
 225 2015-01-31  204400.0
 226 2015-02-28  203500.0
 227 2015-03-31  199800.0
 228 2015-04-30  199000.0
 229 2015-05-31  197700.0
 230 2015-06-30  197300.0
 231 2015-07-31  200400.0
 232 2015-08-31  203100.0
 233 2015-09-30  204400.0
 234 2015-10-31  204800.0
 235 2015-11-30  205700.0
 236 2015-12-31  208600.0
 237 2016-01-31  210100.0
 238 2016-02-29  210900.0
 239 2016-03-31  213100.0
 240 2016-04-30  210800.0
 241 2016-05-31  207900.0
 242 2016-06-30  209300.0
 243 2016-07-31  210500.0
 244 2016-08-31  211300.0
 245 2016-09-30  213100.0
 246 2016-10-31  213300.0
 247 2016-11-30  214100.0
 248 2016-12-31  214200.0
 249 2017-01-31  214800.0

 [133 rows x 2 columns],           Date     Value
 101 2006-01-31  398000.0
 102 2006-02-28  399600.0
 103 2006-03-31  400500.0
 104 2006-04-30  400900.0
 105 2006-05-31  400900.0
 106 2006-06-30  399900.0
 107 2006-07-31  398500.0
 108 2006-08-31  397800.0
 109 2006-09-30  397300.0
 110 2006-10-31  396700.0
 111 2006-11-30  396100.0
 112 2006-12-31  396000.0
 113 2007-01-31  396300.0
 114 2007-02-28  397000.0
 115 2007-03-31  398200.0
 116 2007-04-30  398600.0
 117 2007-05-31  397600.0
 118 2007-06-30  396500.0
 119 2007-07-31  395900.0
 120 2007-08-31  395600.0
 121 2007-09-30  395200.0
 122 2007-10-31  393800.0
 123 2007-11-30  391300.0
 124 2007-12-31  388600.0
 125 2008-01-31  386200.0
 126 2008-02-29  383700.0
 127 2008-03-31  381300.0
 128 2008-04-30  379600.0
 129 2008-05-31  378200.0
 130 2008-06-30  376300.0
 ..         ...       ...
 204 2014-08-31  463300.0
 205 2014-09-30  465200.0
 206 2014-10-31  467100.0
 207 2014-11-30  469600.0
 208 2014-12-31  472200.0
 209 2015-01-31  474100.0
 210 2015-02-28  476600.0
 211 2015-03-31  480300.0
 212 2015-04-30  484400.0
 213 2015-05-31  487600.0
 214 2015-06-30  486600.0
 215 2015-07-31  489400.0
 216 2015-08-31  493100.0
 217 2015-09-30  497600.0
 218 2015-10-31  500100.0
 219 2015-11-30  495600.0
 220 2015-12-31  497400.0
 221 2016-01-31  499200.0
 222 2016-02-29  500500.0
 223 2016-03-31  500700.0
 224 2016-04-30  498200.0
 225 2016-05-31  511700.0
 226 2016-06-30  516300.0
 227 2016-07-31  513900.0
 228 2016-08-31  515100.0
 229 2016-09-30  523900.0
 230 2016-10-31  527200.0
 231 2016-11-30  531400.0
 232 2016-12-31  535000.0
 233 2017-01-31  540400.0

 [133 rows x 2 columns],           Date     Value
 117 2006-01-31  250600.0
 118 2006-02-28  253000.0
 119 2006-03-31  255200.0
 120 2006-04-30  256600.0
 121 2006-05-31  257100.0
 122 2006-06-30  257300.0
 123 2006-07-31  257000.0
 124 2006-08-31  256100.0
 125 2006-09-30  254700.0
 126 2006-10-31  253300.0
 127 2006-11-30  251600.0
 128 2006-12-31  249400.0
 129 2007-01-31  247000.0
 130 2007-02-28  244900.0
 131 2007-03-31  242700.0
 132 2007-04-30  239900.0
 133 2007-05-31  237000.0
 134 2007-06-30  234200.0
 135 2007-07-31  231300.0
 136 2007-08-31  228100.0
 137 2007-09-30  224900.0
 138 2007-10-31  221800.0
 139 2007-11-30  218700.0
 140 2007-12-31  215200.0
 141 2008-01-31  211100.0
 142 2008-02-29  206600.0
 143 2008-03-31  202100.0
 144 2008-04-30  197800.0
 145 2008-05-31  193600.0
 146 2008-06-30  189500.0
 ..         ...       ...
 220 2014-08-31  164700.0
 221 2014-09-30  165700.0
 222 2014-10-31  166400.0
 223 2014-11-30  167400.0
 224 2014-12-31  168600.0
 225 2015-01-31  169400.0
 226 2015-02-28  169700.0
 227 2015-03-31  170500.0
 228 2015-04-30  171100.0
 229 2015-05-31  171800.0
 230 2015-06-30  172800.0
 231 2015-07-31  174100.0
 232 2015-08-31  176600.0
 233 2015-09-30  178300.0
 234 2015-10-31  179700.0
 235 2015-11-30  180800.0
 236 2015-12-31  182100.0
 237 2016-01-31  183900.0
 238 2016-02-29  185000.0
 239 2016-03-31  186100.0
 240 2016-04-30  187200.0
 241 2016-05-31  188000.0
 242 2016-06-30  189500.0
 243 2016-07-31  191100.0
 244 2016-08-31  192600.0
 245 2016-09-30  196200.0
 246 2016-10-31  198000.0
 247 2016-11-30  200100.0
 248 2016-12-31  201800.0
 249 2017-01-31  203200.0

 [133 rows x 2 columns],           Date     Value
 117 2006-01-31  154900.0
 118 2006-02-28  155100.0
 119 2006-03-31  155300.0
 120 2006-04-30  155600.0
 121 2006-05-31  155900.0
 122 2006-06-30  156400.0
 123 2006-07-31  157100.0
 124 2006-08-31  157500.0
 125 2006-09-30  157700.0
 126 2006-10-31  157900.0
 127 2006-11-30  158100.0
 128 2006-12-31  158000.0
 129 2007-01-31  157600.0
 130 2007-02-28  157400.0
 131 2007-03-31  157400.0
 132 2007-04-30  157400.0
 133 2007-05-31  157500.0
 134 2007-06-30  157600.0
 135 2007-07-31  157500.0
 136 2007-08-31  157400.0
 137 2007-09-30  157300.0
 138 2007-10-31  157000.0
 139 2007-11-30  156500.0
 140 2007-12-31  155900.0
 141 2008-01-31  155300.0
 142 2008-02-29  154600.0
 143 2008-03-31  153700.0
 144 2008-04-30  152600.0
 145 2008-05-31  151400.0
 146 2008-06-30  150400.0
 ..         ...       ...
 220 2014-08-31  135200.0
 221 2014-09-30  136200.0
 222 2014-10-31  137400.0
 223 2014-11-30  138300.0
 224 2014-12-31  138900.0
 225 2015-01-31  139200.0
 226 2015-02-28  139500.0
 227 2015-03-31  139000.0
 228 2015-04-30  139300.0
 229 2015-05-31  139600.0
 230 2015-06-30  140200.0
 231 2015-07-31  141300.0
 232 2015-08-31  143700.0
 233 2015-09-30  140800.0
 234 2015-10-31  141200.0
 235 2015-11-30  142000.0
 236 2015-12-31  143100.0
 237 2016-01-31  144000.0
 238 2016-02-29  144500.0
 239 2016-03-31  144900.0
 240 2016-04-30  145900.0
 241 2016-05-31  147000.0
 242 2016-06-30  147700.0
 243 2016-07-31  148500.0
 244 2016-08-31  149100.0
 245 2016-09-30  149800.0
 246 2016-10-31  150800.0
 247 2016-11-30  151400.0
 248 2016-12-31  152400.0
 249 2017-01-31  153000.0

 [133 rows x 2 columns],           Date     Value
 117 2006-01-31  525500.0
 118 2006-02-28  531600.0
 119 2006-03-31  536800.0
 120 2006-04-30  541000.0
 121 2006-05-31  543400.0
 122 2006-06-30  543900.0
 123 2006-07-31  543500.0
 124 2006-08-31  542600.0
 125 2006-09-30  541400.0
 126 2006-10-31  540700.0
 127 2006-11-30  540500.0
 128 2006-12-31  539500.0
 129 2007-01-31  537700.0
 130 2007-02-28  536400.0
 131 2007-03-31  536200.0
 132 2007-04-30  535700.0
 133 2007-05-31  534900.0
 134 2007-06-30  534300.0
 135 2007-07-31  534000.0
 136 2007-08-31  533200.0
 137 2007-09-30  531900.0
 138 2007-10-31  530500.0
 139 2007-11-30  528900.0
 140 2007-12-31  526100.0
 141 2008-01-31  522500.0
 142 2008-02-29  518700.0
 143 2008-03-31  515200.0
 144 2008-04-30  512400.0
 145 2008-05-31  510200.0
 146 2008-06-30  507300.0
 ..         ...       ...
 220 2014-08-31  523900.0
 221 2014-09-30  526500.0
 222 2014-10-31  529400.0
 223 2014-11-30  533100.0
 224 2014-12-31  536600.0
 225 2015-01-31  538900.0
 226 2015-02-28  540900.0
 227 2015-03-31  546100.0
 228 2015-04-30  538500.0
 229 2015-05-31  537300.0
 230 2015-06-30  538400.0
 231 2015-07-31  544600.0
 232 2015-08-31  549000.0
 233 2015-09-30  546300.0
 234 2015-10-31  549000.0
 235 2015-11-30  550900.0
 236 2015-12-31  553000.0
 237 2016-01-31  555100.0
 238 2016-02-29  556700.0
 239 2016-03-31  556200.0
 240 2016-04-30  557500.0
 241 2016-05-31  561700.0
 242 2016-06-30  564600.0
 243 2016-07-31  565600.0
 244 2016-08-31  569100.0
 245 2016-09-30  575100.0
 246 2016-10-31  580400.0
 247 2016-11-30  585900.0
 248 2016-12-31  586100.0
 249 2017-01-31  589300.0

 [133 rows x 2 columns],           Date     Value
 117 2006-01-31  159900.0
 118 2006-02-28  163200.0
 119 2006-03-31  167000.0
 120 2006-04-30  171400.0
 121 2006-05-31  175400.0
 122 2006-06-30  179500.0
 123 2006-07-31  182900.0
 124 2006-08-31  185500.0
 125 2006-09-30  187600.0
 126 2006-10-31  189100.0
 127 2006-11-30  189600.0
 128 2006-12-31  189800.0

In [16]:
#Assigning the data of AL to a new data frame called house_prices
house_prices= AL

In [17]:
#Viewing the house_prices data frame
house_prices

          Date     Value
117 2006-01-31  124000.0
118 2006-02-28  124700.0
119 2006-03-31  125200.0
120 2006-04-30  125600.0
121 2006-05-31  126100.0
122 2006-06-30  126600.0
123 2006-07-31  127200.0
124 2006-08-31  127600.0
125 2006-09-30  127700.0
126 2006-10-31  127800.0
127 2006-11-30  128300.0
128 2006-12-31  129100.0
129 2007-01-31  129400.0
130 2007-02-28  129300.0
131 2007-03-31  129300.0
132 2007-04-30  129300.0
133 2007-05-31  129200.0
134 2007-06-30  129300.0
135 2007-07-31  129700.0
136 2007-08-31  129900.0
137 2007-09-30  130000.0
138 2007-10-31  130000.0
139 2007-11-30  129500.0
140 2007-12-31  128400.0
141 2008-01-31  127400.0
142 2008-02-29  126800.0
143 2008-03-31  126500.0
144 2008-04-30  126500.0
145 2008-05-31  126700.0
146 2008-06-30  127300.0
..         ...       ...
220 2014-08-31  121100.0
221 2014-09-30  121400.0
222 2014-10-31  121800.0
223 2014-11-30  122000.0
224 2014-12-31  121800.0
225 2015-01-31  121400.0
226 2015-02-28  120600.0
227 2015-03-31  120600.0
228 2015-04-30  120600.0
229 2015-05-31  121300.0
230 2015-06-30  122000.0
231 2015-07-31  121700.0
232 2015-08-31  122300.0
233 2015-09-30  122800.0
234 2015-10-31  122200.0
235 2015-11-30  122600.0
236 2015-12-31  122700.0
237 2016-01-31  123100.0
238 2016-02-29  123100.0
239 2016-03-31  122900.0
240 2016-04-30  123300.0
241 2016-05-31  122900.0
242 2016-06-30  122700.0
243 2016-07-31  122300.0
244 2016-08-31  122300.0
245 2016-09-30  122500.0
246 2016-10-31  122800.0
247 2016-11-30  123200.0
248 2016-12-31  123800.0
249 2017-01-31  124600.0

[133 rows x 2 columns]

In [18]:
# In the following 106 rows I will be Joining tha Value column of each state data frame to the house_prices data frame, such as
# house_prices = house_prices.merge(AK,how='left', left_on='Date', right_on='Date')
# matching by Date.  When a column is added to the house_prices data frame it carries over the same name of the column
# which in every case is Value, therefore I will also need to rename each coulm as it is joined to the house_prices
# data frame using the following command - 
# house_prices.rename(columns={'Value_x':'Name of data frame','Value_y':'name of data frame'}, inplace=True)

In [19]:

house_prices = house_prices.merge(AK,how='left', left_on='Date', right_on='Date')

In [20]:
house_prices

          Date   Value_x   Value_y
0   2006-01-31  124000.0  235100.0
1   2006-02-28  124700.0  237100.0
2   2006-03-31  125200.0  238700.0
3   2006-04-30  125600.0  239000.0
4   2006-05-31  126100.0  238500.0
5   2006-06-30  126600.0  237700.0
6   2006-07-31  127200.0  236100.0
7   2006-08-31  127600.0  234700.0
8   2006-09-30  127700.0  235300.0
9   2006-10-31  127800.0  237200.0
10  2006-11-30  128300.0  239000.0
11  2006-12-31  129100.0  243500.0
12  2007-01-31  129400.0  249500.0
13  2007-02-28  129300.0  255300.0
14  2007-03-31  129300.0  258800.0
15  2007-04-30  129300.0  261500.0
16  2007-05-31  129200.0  261900.0
17  2007-06-30  129300.0  262700.0
18  2007-07-31  129700.0  264000.0
19  2007-08-31  129900.0  265600.0
20  2007-09-30  130000.0  265700.0
21  2007-10-31  130000.0  265500.0
22  2007-11-30  129500.0  264700.0
23  2007-12-31  128400.0  265900.0
24  2008-01-31  127400.0  267800.0
25  2008-02-29  126800.0  268200.0
26  2008-03-31  126500.0  267200.0
27  2008-04-30  126500.0  268400.0
28  2008-05-31  126700.0  269900.0
29  2008-06-30  127300.0  271300.0
..         ...       ...       ...
103 2014-08-31  121100.0  255600.0
104 2014-09-30  121400.0  254400.0
105 2014-10-31  121800.0  253600.0
106 2014-11-30  122000.0  253300.0
107 2014-12-31  121800.0  254900.0
108 2015-01-31  121400.0  257200.0
109 2015-02-28  120600.0  258000.0
110 2015-03-31  120600.0  257300.0
111 2015-04-30  120600.0  257200.0
112 2015-05-31  121300.0  258100.0
113 2015-06-30  122000.0  259500.0
114 2015-07-31  121700.0  260500.0
115 2015-08-31  122300.0  262000.0
116 2015-09-30  122800.0  262200.0
117 2015-10-31  122200.0  262400.0
118 2015-11-30  122600.0  262700.0
119 2015-12-31  122700.0  264100.0
120 2016-01-31  123100.0  265400.0
121 2016-02-29  123100.0  266200.0
122 2016-03-31  122900.0  267500.0
123 2016-04-30  123300.0  268600.0
124 2016-05-31  122900.0  266500.0
125 2016-06-30  122700.0  266400.0
126 2016-07-31  122300.0  266500.0
127 2016-08-31  122300.0  266800.0
128 2016-09-30  122500.0  265300.0
129 2016-10-31  122800.0  265300.0
130 2016-11-30  123200.0  265700.0
131 2016-12-31  123800.0  266300.0
132 2017-01-31  124600.0  267000.0

[133 rows x 3 columns]

In [21]:
#Renaming the column headings
house_prices.rename(columns={'Value_x':'AL','Value_y':'AK'}, inplace=True)

In [22]:
house_prices.head()

        Date        AL        AK
0 2006-01-31  124000.0  235100.0
1 2006-02-28  124700.0  237100.0
2 2006-03-31  125200.0  238700.0
3 2006-04-30  125600.0  239000.0
4 2006-05-31  126100.0  238500.0

In [23]:
#Joining tha Value column of AZ to the house_prices data frame, matching by Date
house_prices = house_prices.merge(AZ,how='left', left_on='Date', right_on='Date')

In [24]:
house_prices.head()

        Date        AL        AK     Value
0 2006-01-31  124000.0  235100.0  259900.0
1 2006-02-28  124700.0  237100.0  261600.0
2 2006-03-31  125200.0  238700.0  262900.0
3 2006-04-30  125600.0  239000.0  263500.0
4 2006-05-31  126100.0  238500.0  263500.0

In [25]:
house_prices.rename(columns={'Value':'AZ'}, inplace=True)

In [26]:
house_prices.head()

        Date        AL        AK        AZ
0 2006-01-31  124000.0  235100.0  259900.0
1 2006-02-28  124700.0  237100.0  261600.0
2 2006-03-31  125200.0  238700.0  262900.0
3 2006-04-30  125600.0  239000.0  263500.0
4 2006-05-31  126100.0  238500.0  263500.0

In [27]:
house_prices = house_prices.merge(AR,how='left', left_on='Date', right_on='Date')

In [28]:
house_prices.head()

        Date        AL        AK        AZ    Value
0 2006-01-31  124000.0  235100.0  259900.0  93200.0
1 2006-02-28  124700.0  237100.0  261600.0  93600.0
2 2006-03-31  125200.0  238700.0  262900.0  94200.0
3 2006-04-30  125600.0  239000.0  263500.0  94500.0
4 2006-05-31  126100.0  238500.0  263500.0  94800.0

In [29]:
house_prices.rename(columns={'Value':'AR'}, inplace=True)

In [30]:
house_prices.head()

        Date        AL        AK        AZ       AR
0 2006-01-31  124000.0  235100.0  259900.0  93200.0
1 2006-02-28  124700.0  237100.0  261600.0  93600.0
2 2006-03-31  125200.0  238700.0  262900.0  94200.0
3 2006-04-30  125600.0  239000.0  263500.0  94500.0
4 2006-05-31  126100.0  238500.0  263500.0  94800.0

In [31]:
house_prices = house_prices.merge(CA,how='left', left_on='Date', right_on='Date')

In [32]:
house_prices.rename(columns={'Value':'CA'}, inplace=True)

In [33]:
house_prices = house_prices.merge(CO,how='left', left_on='Date', right_on='Date')

In [34]:
house_prices.rename(columns={'Value':'CO'}, inplace=True)

In [35]:
house_prices = house_prices.merge(CT,how='left', left_on='Date', right_on='Date')

In [36]:
house_prices.rename(columns={'Value':'CT'}, inplace=True)

In [37]:
house_prices = house_prices.merge(DC,how='left', left_on='Date', right_on='Date')

In [38]:
house_prices.rename(columns={'Value':'DC'}, inplace=True)

In [39]:
house_prices = house_prices.merge(DE,how='left', left_on='Date', right_on='Date')

In [40]:
house_prices.rename(columns={'Value':'DE'}, inplace=True)

In [41]:
house_prices = house_prices.merge(FL,how='left', left_on='Date', right_on='Date')

In [42]:
house_prices.rename(columns={'Value':'FL'}, inplace=True)

In [43]:
house_prices = house_prices.merge(GA,how='left', left_on='Date', right_on='Date')

In [44]:
house_prices.rename(columns={'Value':'GA'}, inplace=True)

In [45]:
house_prices = house_prices.merge(HI,how='left', left_on='Date', right_on='Date')

In [46]:
house_prices.rename(columns={'Value':'HI'}, inplace=True)

In [47]:
house_prices = house_prices.merge(ID,how='left', left_on='Date', right_on='Date')

In [48]:
house_prices.rename(columns={'Value':'ID'}, inplace=True)

In [49]:
house_prices = house_prices.merge(IL,how='left', left_on='Date', right_on='Date')

In [50]:
house_prices.rename(columns={'Value':'IL'}, inplace=True)

In [51]:
house_prices = house_prices.merge(IN,how='left', left_on='Date', right_on='Date')

In [52]:
house_prices.rename(columns={'Value':'IN'}, inplace=True)

In [53]:
house_prices = house_prices.merge(IA,how='left', left_on='Date', right_on='Date')

In [54]:
house_prices.rename(columns={'Value':'IA'}, inplace=True)

In [55]:
house_prices = house_prices.merge(KS,how='left', left_on='Date', right_on='Date')

In [56]:
house_prices.rename(columns={'Value':'KS'}, inplace=True)

In [57]:
house_prices = house_prices.merge(KY,how='left', left_on='Date', right_on='Date')

In [58]:
house_prices.rename(columns={'Value':'KY'}, inplace=True)

In [59]:
house_prices = house_prices.merge(LA,how='left', left_on='Date', right_on='Date')

In [60]:
house_prices.rename(columns={'Value':'LA'}, inplace=True)

In [61]:
house_prices = house_prices.merge(ME,how='left', left_on='Date', right_on='Date')

In [62]:
house_prices.rename(columns={'Value':'ME'}, inplace=True)

In [63]:
house_prices = house_prices.merge(MD,how='left', left_on='Date', right_on='Date')

In [64]:
house_prices.rename(columns={'Value':'MD'}, inplace=True)

In [65]:
house_prices = house_prices.merge(MA,how='left', left_on='Date', right_on='Date')

In [66]:
house_prices.rename(columns={'Value':'MA'}, inplace=True)

In [67]:
house_prices = house_prices.merge(MI,how='left', left_on='Date', right_on='Date')

In [68]:
house_prices.rename(columns={'Value':'MI'}, inplace=True)

In [69]:
house_prices = house_prices.merge(MN,how='left', left_on='Date', right_on='Date')

In [70]:
house_prices.rename(columns={'Value':'MN'}, inplace=True)

In [71]:
house_prices = house_prices.merge(MS,how='left', left_on='Date', right_on='Date')

In [72]:
house_prices.rename(columns={'Value':'MS'}, inplace=True)

In [73]:
house_prices = house_prices.merge(MO,how='left', left_on='Date', right_on='Date')

In [74]:
house_prices.rename(columns={'Value':'MO'}, inplace=True)

In [75]:
house_prices = house_prices.merge(MT,how='left', left_on='Date', right_on='Date')

In [76]:
house_prices.rename(columns={'Value':'MT'}, inplace=True)

In [77]:
house_prices = house_prices.merge(NE,how='left', left_on='Date', right_on='Date')

In [78]:
house_prices.rename(columns={'Value':'NE'}, inplace=True)

In [79]:
house_prices = house_prices.merge(NV,how='left', left_on='Date', right_on='Date')

In [80]:
house_prices.rename(columns={'Value':'NV'}, inplace=True)

In [81]:
house_prices = house_prices.merge(NH,how='left', left_on='Date', right_on='Date')

In [82]:
house_prices.rename(columns={'Value':'NH'}, inplace=True)

In [83]:
house_prices = house_prices.merge(NJ,how='left', left_on='Date', right_on='Date')

In [84]:
house_prices.rename(columns={'Value':'NJ'}, inplace=True)

In [85]:
house_prices = house_prices.merge(NM,how='left', left_on='Date', right_on='Date')

In [86]:
house_prices.rename(columns={'Value':'NM'}, inplace=True)

In [87]:
house_prices = house_prices.merge(NY,how='left', left_on='Date', right_on='Date')

In [88]:
house_prices.rename(columns={'Value':'NY'}, inplace=True)

In [89]:
house_prices = house_prices.merge(NC,how='left', left_on='Date', right_on='Date')

In [90]:
house_prices.rename(columns={'Value':'NC'}, inplace=True)

In [91]:
house_prices = house_prices.merge(ND,how='left', left_on='Date', right_on='Date')

In [92]:
house_prices.rename(columns={'Value':'ND'}, inplace=True)

In [93]:
house_prices = house_prices.merge(OH,how='left', left_on='Date', right_on='Date')

In [94]:
house_prices.rename(columns={'Value':'OH'}, inplace=True)

In [95]:
house_prices = house_prices.merge(OK,how='left', left_on='Date', right_on='Date')

In [96]:
house_prices.rename(columns={'Value':'OK'}, inplace=True)

In [97]:
house_prices = house_prices.merge(OR,how='left', left_on='Date', right_on='Date')

In [98]:
house_prices.rename(columns={'Value':'OR'}, inplace=True)

In [99]:
house_prices = house_prices.merge(PA,how='left', left_on='Date', right_on='Date')

In [100]:
house_prices.rename(columns={'Value':'PA'}, inplace=True)

In [101]:
house_prices = house_prices.merge(RI,how='left', left_on='Date', right_on='Date')

In [102]:
house_prices.rename(columns={'Value':'RI'}, inplace=True)

In [103]:
house_prices = house_prices.merge(SC,how='left', left_on='Date', right_on='Date')

In [104]:
house_prices.rename(columns={'Value':'SC'}, inplace=True)

In [105]:
house_prices = house_prices.merge(SD,how='left', left_on='Date', right_on='Date')

In [106]:
house_prices.rename(columns={'Value':'SD'}, inplace=True)

In [107]:
house_prices = house_prices.merge(TN,how='left', left_on='Date', right_on='Date')

In [108]:
house_prices.rename(columns={'Value':'TN'}, inplace=True)

In [109]:
house_prices = house_prices.merge(TX,how='left', left_on='Date', right_on='Date')

In [110]:
house_prices.rename(columns={'Value':'TX'}, inplace=True)

In [111]:
house_prices = house_prices.merge(UT,how='left', left_on='Date', right_on='Date')

In [112]:
house_prices.rename(columns={'Value':'UT'}, inplace=True)

In [113]:
house_prices = house_prices.merge(VT,how='left', left_on='Date', right_on='Date')

In [114]:
house_prices.rename(columns={'Value':'VT'}, inplace=True)

In [115]:
house_prices = house_prices.merge(VA,how='left', left_on='Date', right_on='Date')

In [116]:
house_prices.rename(columns={'Value':'VA'}, inplace=True)

In [117]:
house_prices = house_prices.merge(WA,how='left', left_on='Date', right_on='Date')

In [118]:
house_prices.rename(columns={'Value':'WA'}, inplace=True)

In [119]:
house_prices = house_prices.merge(WV,how='left', left_on='Date', right_on='Date')

In [120]:
house_prices.rename(columns={'Value':'WV'}, inplace=True)

In [121]:
house_prices = house_prices.merge(WI,how='left', left_on='Date', right_on='Date')

In [122]:
house_prices.rename(columns={'Value':'WI'}, inplace=True)

In [123]:
house_prices = house_prices.merge(WY,how='left', left_on='Date', right_on='Date')

In [124]:
house_prices.rename(columns={'Value':'WY'}, inplace=True)

In [125]:
#Renaming the column headings
#house_prices.rename(columns={'Value_x':'AL','Value_y':'AK'}, inplace=True)

In [126]:
# Viewing the complete house_prices data frame
house_prices

,Date,AL,AK,AZ,AR,CA,CO,CT,DC,DE,...,SD,TN,TX,UT,VT,VA,WA,WV,WI,WY
0,2006-01-31,124000.0,235100.0,259900.0,93200.0,534500.0,222500.0,294300.0,398000.0,225000.0,...,130900.0,115000.0,124100.0,193000.0,NaN,261300.0,271100.0,NaN,163800.0,NaN
1,2006-02-28,124700.0,237100.0,261600.0,93600.0,536100.0,223300.0,294900.0,399600.0,226100.0,...,131100.0,115500.0,125100.0,195700.0,NaN,262200.0,274100.0,NaN,164300.0,NaN
2,2006-03-31,125200.0,238700.0,262900.0,94200.0,537500.0,223400.0,295400.0,400500.0,227200.0,...,132000.0,115800.0,127400.0,198300.0,NaN,263000.0,276900.0,NaN,164600.0,NaN
3,2006-04-30,125600.0,239000.0,263500.0,94500.0,538300.0,223600.0,296000.0,400900.0,228000.0,...,132600.0,116300.0,127300.0,201000.0,NaN,263900.0,279800.0,NaN,164700.0,NaN
4,2006-05-31,126100.0,238500.0,263500.0,94800.0,538300.0,223700.0,296100.0,400900.0,228500.0,...,132500.0,117000.0,126600.0,204200.0,NaN,264800.0,282700.0,NaN,164600.0,NaN
5,2006-06-30,126600.0,237700.0,263000.0,94800.0,537700.0,223500.0,296100.0,399900.0,229200.0,...,132200.0,117700.0,127100.0,207800.0,NaN,265700.0,285400.0,NaN,164200.0,NaN
6,2006-07-31,127200.0,236100.0,262100.0,95100.0,536600.0,223800.0,295800.0,398500.0,230000.0,...,132400.0,118300.0,128700.0,211900.0,NaN,266400.0,288100.0,NaN,163700.0,NaN
7,2006-08-31,127600.0,234700.0,260900.0,95700.0,534800.0,224400.0,295400.0,397800.0,230400.0,...,133200.0,118800.0,128400.0,215600.0,NaN,267000.0,290600.0,NaN,163400.0,NaN
8,2006-09-30,127700.0,235300.0,259400.0,95800.0,532400.0,224700.0,294900.0,397300.0,230600.0,...,134100.0,119100.0,128100.0,219600.0,NaN,266800.0,292700.0,NaN,163600.0,NaN
9,2006-10-31,127800.0,237200.0,257700.0,95300.0,529600.0,225300.0,294700.0,396700.0,231100.0,...,135500.0,119600.0,129100.0,223800.0,NaN,266000.0,294400.0,NaN,164100.0,NaN
10,2006-11-30,128300.0,239000.0,256100.0,95400.0,527000.0,226300.0,294300.0,396100.0,232000.0,...,137100.0,120400.0,131000.0,227300.0,NaN,265400.0,296200.0,NaN,164300.0,NaN
11,2006-12-31,129100.0,243500.0,254300.0,95900.0,523900.0,227100.0,293800.0,396000.0,232600.0,...,137100.0,121000.0,132300.0,230600.0,NaN,265400.0,297600.0,NaN,164400.0,NaN
12,2007-01-31,129400.0,249500.0,252300.0,96300.0,521000.0,226900.0,293500.0,396300.0,232800.0,...,136400.0,121200.0,133600.0,234900.0,NaN,265400.0,298500.0,NaN,164700.0,NaN
13,2007-02-28,129300.0,255300.0,250300.0,96600.0,518700.0,226300.0,293600.0,397000.0,232600.0,...,136900.0,121500.0,132800.0,239300.0,NaN,265300.0,299200.0,NaN,164700.0,NaN
14,2007-03-31,129300.0,258800.0,248400.0,97100.0,516700.0,226100.0,293800.0,398200.0,232900.0,...,138400.0,121900.0,131600.0,243400.0,NaN,265300.0,300100.0,NaN,165000.0,NaN
15,2007-04-30,129300.0,261500.0,246700.0,97500.0,513900.0,226000.0,293900.0,398600.0,233200.0,...,139200.0,122200.0,132500.0,247000.0,NaN,265300.0,300700.0,NaN,165800.0,NaN
16,2007-05-31,129200.0,261900.0,245000.0,97700.0,510500.0,226200.0,293400.0,397600.0,233100.0,...,140200.0,122300.0,134200.0,249300.0,NaN,265200.0,301000.0,NaN,166400.0,NaN
17,2007-06-30,129300.0,262700.0,243300.0,97900.0,506100.0,226900.0,292400.0,396500.0,232500.0,...,140500.0,122400.0,134600.0,251000.0,NaN,263600.0,300900.0,NaN,166000.0,NaN
18,2007-07-31,129700.0,264000.0,241700.0,98300.0,501200.0,227500.0,291400.0,395900.0,232300.0,...,139100.0,122400.0,134700.0,252500.0,NaN,260200.0,300800.0,NaN,165400.0,NaN
19,2007-08-31,129900.0,265600.0,240200.0,98500.0,496200.0,226900.0,290500.0,395600.0,232000.0,...,137600.0,122600.0,135000.0,254100.0,NaN,256000.0,300500.0,NaN,165000.0,NaN
20,2007-09-30,130000.0,265700.0,238600.0,98700.0,490900.0,226900.0,289500.0,395200.0,231300.0,...,137100.0,122800.0,135500.0,255500.0,NaN,255400.0,299600.0,NaN,164600.0,NaN
21,2007-10-31,130000.0,265500.0,236900.0,99300.0,485400.0,227100.0,288400.0,393800.0,230500.0,...,135900.0,122800.0,135100.0,256700.0,NaN,257500.0,298200.0,NaN,164400.0,NaN
22,2007-11-30,129500.0,264700.0,234900.0,99900.0,479300.0,226700.0,287500.0,391300.0,229800.0,...,134900.0,122600.0,134500.0,258000.0,NaN,258000.0,296700.0,NaN,164100.0,NaN
23,2007-12-31,128400.0,265900.0,232200.0,99600.0,471900.0,224800.0,286100.0,388600.0,228900.0,...,135000.0,122300.0,135000.0,259800.0,NaN,255800.0,294900.0,NaN,163900.0,NaN
24,2008-01-31,127400.0,267800.0,228500.0,99300.0,463300.0,222300.0,284300.0,386200.0,227900.0,...,135300.0,121900.0,135400.0,261300.0,NaN,253900.0,292900.0,NaN,163100.0,NaN
25,2008-02-29,126800.0,268200.0,224500.0,99200.0,454100.0,220000.0,282500.0,383700.0,226800.0,...,135600.0,121600.0,134200.0,259900.0,NaN,251800.0,291000.0,NaN,162600.0,NaN
26,2008-03-31,126500.0,267200.0,220500.0,99400.0,443900.0,219100.0,280900.0,381300.0,225400.0,...,135900.0,121600.0,132300.0,256300.0,NaN,249600.0,289100.0,NaN,162600.0,NaN
27,2008-04-30,126500.0,268400.0,216700.0,99400.0,433300.0,218600.0,279500.0,379600.0,223800.0,...,136200.0,121300.0,131100.0,254000.0,NaN,247300.0,287400.0,NaN,162900.0,NaN
28,2008-05-31,126700.0,269900.0,213300.0,99100.0,423000.0,218600.0,278100.0,378200.0,222300.0,...,136200.0,121000.0,129600.0,253300.0,NaN,244900.0,285400.0,NaN,162600.0,NaN
29,2008-06-30,127300.0,271300.0,209700.0,98800.0,413200.0,218800.0,276800.0,376300.0,221000.0,...,136300.0,120700.0,128300.0,252700.0,NaN,242500.0,282900.0,NaN,162500.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,2014-08-31,121100.0,255600.0,185000.0,110900.0,427400.0,249100.0,240600.0,463300.0,202700.0,...,123200.0,125300.0,135000.0,206800.0,218700.0,230100.0,258500.0,99300.0,153600.0,NaN
104,2014-09-30,121400.0,254400.0,186500.0,111800.0,429400.0,251400.0,240200.0,465200.0,203700.0,...,123000.0,126000.0,135600.0,206600.0,219700.0,230400.0,259400.0,98100.0,154000.0,NaN
105,2014-10-31,121800.0,253600.0,188100.0,112700.0,431500.0,254000.0,239900.0,467100.0,204800.0,...,123200.0,126500.0,136200.0,206900.0,219900.0,231200.0,260700.0,96300.0,154400.0,NaN
106,2014-11-30,122000.0,253300.0,189700.0,113600.0,433500.0,257000.0,239700.0,469600.0,205400.0,...,123700.0,127100.0,136800.0,207200.0,220300.0,232400.0,262600.0,95500.0,154700.0,NaN
107,2014-12-31,121800.0,254900.0,191200.0,114500.0,435300.0,260500.0,239600.0,472200.0,205200.0,...,123900.0,127500.0,138000.0,207800.0,220200.0,233100.0,264500.0,94900.0,154700.0,NaN
108,2015-01-31,121400.0,257200.0,192100.0,115100.0,436600.0,263200.0,239500.0,474100.0,204400.0,...,123700.0,127700.0,139200.0,208600.0,219200.0,233300.0,265800.0,93600.0,154400.0,NaN
109,2015-02-28,120600.0,258000.0,192500.0,114800.0,439500.0,265700.0,237100.0,476600.0,203500.0,...,123500.0,127600.0,140600.0,209100.0,220300.0,232600.0,268400.0,91200.0,153800.0,NaN
110,2015-03-31,120600.0,257300.0,191800.0,114000.0,440000.0,267100.0,239800.0,480300.0,199800.0,...,119400.0,127600.0,141000.0,208900.0,220900.0,231000.0,268800.0,90700.0,152600.0,NaN
111,2015-04-30,120600.0,257200.0,191300.0,114200.0,440700.0,268700.0,236500.0,484400.0,199000.0,...,165300.0,127300.0,142100.0,209300.0,219600.0,230800.0,270400.0,90300.0,153000.0,NaN
112,2015-05-31,121300.0,258100.0,191300.0,114500.0,441800.0,271300.0,236800.0,487600.0,197700.0,...,167700.0,127600.0,143600.0,210500.0,217400.0,230500.0,272900.0,91300.0,152900.0,NaN
113,2015-06-30,122000.0,259500.0,192300.0,114000.0,443200.0,274400.0,237300.0,486600.0,197300.0,...,168200.0,128300.0,144700.0,212000.0,217700.0,230900.0,275000.0,93100.0,154400.0,NaN
114,2015-07-31,121700.0,260500.0,193900.0,113800.0,445500.0,277300.0,237600.0,489400.0,200400.0,...,166100.0,129100.0,145500.0,213700.0,218400.0,230200.0,275900.0,89800.0,155900.0,NaN
115,2015-08-31,122300.0,262000.0,196400.0,113500.0,448400.0,279700.0,237800.0,493100.0,203100.0,...,166600.0,127900.0,149700.0,217400.0,218900.0,232100.0,277000.0,90900.0,154000.0,190800.0
116,2015-09-30,122800.0,262200.0,198600.0,114400.0,447500.0,282200.0,238500.0,497600.0,204400.0,...,171400.0,128900.0,150100.0,219100.0,218500.0,230700.0,279600.0,92300.0,155700.0,191700.0
117,2015-10-31,122200.0,262400.0,199900.0,114000.0,449200.0,284000.0,238000.0,500100.0,204800.0,...,173400.0,129100.0,150600.0,220300.0,218800.0,231100.0,282500.0,93500.0,156700.0,192200.0
118,2015-11-30,122600.0,262700.0,202600.0,114800.0,452300.0,286500.0,237200.0,495600.0,205700.0,...,173900.0,129700.0,151100.0,221200.0,218700.0,231500.0,284600.0,92600.0,156700.0,192400.0
119,2015-12-31,122700.0,264100.0,203600.0,114900.0,454600.0,290100.0,237400.0,497400.0,208600.0,...,174800.0,130300.0,151800.0,222300.0,218000.0,231800.0,286300.0,93900.0,156500.0,192500.0
120,2016-01-31,123100.0,265400.0,204600.0,115200.0,456800.0,292500.0,237700.0,499200.0,210100.0,...,176700.0,130600.0,152600.0,223400.0,218600.0,231800.0,287300.0,96200.0,155800.0,192600.0
121,2016-02-29,123100.0,266200.0,205000.0,115300.0,458500.0,294200.0,237900.0,500500.0,210900.0,...,177800.0,130900.0,153300.0,224300.0,218200.0,231700.0,288600.0,98600.0,155200.0,192600.0
122,2016-03-31,122900.0,267500.0,206100.0,115400.0,462100.0,298500.0,238600.0,500700.0,213100.0,...,176900.0,131500.0,154400.0,225800.0,217500.0,233100.0,294300.0,95700.0,154900.0,193300.0
123,2016-04-30,123300.0,268600.0,207000.0,116500.0,463600.0,302200.0,236200.0,498200.0,210800.0,...,164000.0,132100.0,155400.0,227200.0,216500.0,233800.0,296500.0,96600.0,155600.0,193800.0
124,2016-05-31,122900.0,266500.0,207300.0,114700.0,464200.0,301200.0,238900.0,511700.0,207900.0,...,162900.0,132400.0,156200.0,228100.0,208500.0,234300.0,298700.0,98800.0,155100.0,193600.0
125,2016-06-30,122700.0,266400.0,208000.0,114800.0,466300.0,303600.0,239300.0,516300.0,209300.0,...,172800.0,133500.0,157000.0,229200.0,209300.0,234800.0,301500.0,99500.0,156000.0,194000.0
126,2016-07-31,122300.0,266500.0,208800.0,114400.0,467000.0,305300.0,239700.0,513900.0,210500.0,...,175100.0,134400.0,158100.0,231000.0,211600.0,235400.0,303300.0,99700.0,157400.0,194200.0
127,2016-08-31,122300.0,266800.0,210200.0,115000.0,469500.0,308000.0,240500.0,515100.0,211300.0,...,175300.0,135200.0,159200.0,232300.0,212400.0,235800.0,305800.0,100900.0,158500.0,194400.0
128,2016-09-30,122500.0,265300.0,213200.0,114100.0,476700.0,313700.0,241500.0,523900.0,213100.0,...,163100.0,134300.0,160800.0,236500.0,213800.0,237400.0,311300.0,99100.0,158200.0,193500.0
129,2016-10-31,122800.0,265300.0,214700.0,114900.0,479700.0,316200.0,242300.0,527200.0,213300.0,...,169900.0,135500.0,161300.0,238200.0,NaN,238500.0,313800.0,100200.0,159100.0,193900.0
130,2016-11-30,123200.0,265700.0,216200.0,115300.0,483200.0,318700.0,242900.0,531400.0,214100.0,...,170600.0,136700.0,161800.0,239300.0,NaN,239500.0,316500.0,101600.0,159900.0,194000.0
131,2016-12-31,123800.0,266300.0,217900.0,116100.0,485900.0,320900.0,243100.0,535000.0,214200.0,...,171600.0,137300.0,162400.0,240700.0,NaN,240400.0,317700.0,102000.0,160800.0,194000.0
132,2017-01-31,124600.0,267000.0,219000.0,116700.0,487700.0,322300.0,243300.0,540400.0,214800.0,...,172100.0,138000.0,163100.0,242300.0,NaN,241000.0,318300.0,102400.0,161500.0,194000.0

In [127]:
# Replacing any NAN values with 0
house_prices = house_prices.fillna(0)

In [128]:
# Viewing the changes
house_prices

,Date,AL,AK,AZ,AR,CA,CO,CT,DC,DE,...,SD,TN,TX,UT,VT,VA,WA,WV,WI,WY
0,2006-01-31,124000.0,235100.0,259900.0,93200.0,534500.0,222500.0,294300.0,398000.0,225000.0,...,130900.0,115000.0,124100.0,193000.0,0.0,261300.0,271100.0,0.0,163800.0,0.0
1,2006-02-28,124700.0,237100.0,261600.0,93600.0,536100.0,223300.0,294900.0,399600.0,226100.0,...,131100.0,115500.0,125100.0,195700.0,0.0,262200.0,274100.0,0.0,164300.0,0.0
2,2006-03-31,125200.0,238700.0,262900.0,94200.0,537500.0,223400.0,295400.0,400500.0,227200.0,...,132000.0,115800.0,127400.0,198300.0,0.0,263000.0,276900.0,0.0,164600.0,0.0
3,2006-04-30,125600.0,239000.0,263500.0,94500.0,538300.0,223600.0,296000.0,400900.0,228000.0,...,132600.0,116300.0,127300.0,201000.0,0.0,263900.0,279800.0,0.0,164700.0,0.0
4,2006-05-31,126100.0,238500.0,263500.0,94800.0,538300.0,223700.0,296100.0,400900.0,228500.0,...,132500.0,117000.0,126600.0,204200.0,0.0,264800.0,282700.0,0.0,164600.0,0.0
5,2006-06-30,126600.0,237700.0,263000.0,94800.0,537700.0,223500.0,296100.0,399900.0,229200.0,...,132200.0,117700.0,127100.0,207800.0,0.0,265700.0,285400.0,0.0,164200.0,0.0
6,2006-07-31,127200.0,236100.0,262100.0,95100.0,536600.0,223800.0,295800.0,398500.0,230000.0,...,132400.0,118300.0,128700.0,211900.0,0.0,266400.0,288100.0,0.0,163700.0,0.0
7,2006-08-31,127600.0,234700.0,260900.0,95700.0,534800.0,224400.0,295400.0,397800.0,230400.0,...,133200.0,118800.0,128400.0,215600.0,0.0,267000.0,290600.0,0.0,163400.0,0.0
8,2006-09-30,127700.0,235300.0,259400.0,95800.0,532400.0,224700.0,294900.0,397300.0,230600.0,...,134100.0,119100.0,128100.0,219600.0,0.0,266800.0,292700.0,0.0,163600.0,0.0
9,2006-10-31,127800.0,237200.0,257700.0,95300.0,529600.0,225300.0,294700.0,396700.0,231100.0,...,135500.0,119600.0,129100.0,223800.0,0.0,266000.0,294400.0,0.0,164100.0,0.0
10,2006-11-30,128300.0,239000.0,256100.0,95400.0,527000.0,226300.0,294300.0,396100.0,232000.0,...,137100.0,120400.0,131000.0,227300.0,0.0,265400.0,296200.0,0.0,164300.0,0.0
11,2006-12-31,129100.0,243500.0,254300.0,95900.0,523900.0,227100.0,293800.0,396000.0,232600.0,...,137100.0,121000.0,132300.0,230600.0,0.0,265400.0,297600.0,0.0,164400.0,0.0
12,2007-01-31,129400.0,249500.0,252300.0,96300.0,521000.0,226900.0,293500.0,396300.0,232800.0,...,136400.0,121200.0,133600.0,234900.0,0.0,265400.0,298500.0,0.0,164700.0,0.0
13,2007-02-28,129300.0,255300.0,250300.0,96600.0,518700.0,226300.0,293600.0,397000.0,232600.0,...,136900.0,121500.0,132800.0,239300.0,0.0,265300.0,299200.0,0.0,164700.0,0.0
14,2007-03-31,129300.0,258800.0,248400.0,97100.0,516700.0,226100.0,293800.0,398200.0,232900.0,...,138400.0,121900.0,131600.0,243400.0,0.0,265300.0,300100.0,0.0,165000.0,0.0
15,2007-04-30,129300.0,261500.0,246700.0,97500.0,513900.0,226000.0,293900.0,398600.0,233200.0,...,139200.0,122200.0,132500.0,247000.0,0.0,265300.0,300700.0,0.0,165800.0,0.0
16,2007-05-31,129200.0,261900.0,245000.0,97700.0,510500.0,226200.0,293400.0,397600.0,233100.0,...,140200.0,122300.0,134200.0,249300.0,0.0,265200.0,301000.0,0.0,166400.0,0.0
17,2007-06-30,129300.0,262700.0,243300.0,97900.0,506100.0,226900.0,292400.0,396500.0,232500.0,...,140500.0,122400.0,134600.0,251000.0,0.0,263600.0,300900.0,0.0,166000.0,0.0
18,2007-07-31,129700.0,264000.0,241700.0,98300.0,501200.0,227500.0,291400.0,395900.0,232300.0,...,139100.0,122400.0,134700.0,252500.0,0.0,260200.0,300800.0,0.0,165400.0,0.0
19,2007-08-31,129900.0,265600.0,240200.0,98500.0,496200.0,226900.0,290500.0,395600.0,232000.0,...,137600.0,122600.0,135000.0,254100.0,0.0,256000.0,300500.0,0.0,165000.0,0.0
20,2007-09-30,130000.0,265700.0,238600.0,98700.0,490900.0,226900.0,289500.0,395200.0,231300.0,...,137100.0,122800.0,135500.0,255500.0,0.0,255400.0,299600.0,0.0,164600.0,0.0
21,2007-10-31,130000.0,265500.0,236900.0,99300.0,485400.0,227100.0,288400.0,393800.0,230500.0,...,135900.0,122800.0,135100.0,256700.0,0.0,257500.0,298200.0,0.0,164400.0,0.0
22,2007-11-30,129500.0,264700.0,234900.0,99900.0,479300.0,226700.0,287500.0,391300.0,229800.0,...,134900.0,122600.0,134500.0,258000.0,0.0,258000.0,296700.0,0.0,164100.0,0.0
23,2007-12-31,128400.0,265900.0,232200.0,99600.0,471900.0,224800.0,286100.0,388600.0,228900.0,...,135000.0,122300.0,135000.0,259800.0,0.0,255800.0,294900.0,0.0,163900.0,0.0
24,2008-01-31,127400.0,267800.0,228500.0,99300.0,463300.0,222300.0,284300.0,386200.0,227900.0,...,135300.0,121900.0,135400.0,261300.0,0.0,253900.0,292900.0,0.0,163100.0,0.0
25,2008-02-29,126800.0,268200.0,224500.0,99200.0,454100.0,220000.0,282500.0,383700.0,226800.0,...,135600.0,121600.0,134200.0,259900.0,0.0,251800.0,291000.0,0.0,162600.0,0.0
26,2008-03-31,126500.0,267200.0,220500.0,99400.0,443900.0,219100.0,280900.0,381300.0,225400.0,...,135900.0,121600.0,132300.0,256300.0,0.0,249600.0,289100.0,0.0,162600.0,0.0
27,2008-04-30,126500.0,268400.0,216700.0,99400.0,433300.0,218600.0,279500.0,379600.0,223800.0,...,136200.0,121300.0,131100.0,254000.0,0.0,247300.0,287400.0,0.0,162900.0,0.0
28,2008-05-31,126700.0,269900.0,213300.0,99100.0,423000.0,218600.0,278100.0,378200.0,222300.0,...,136200.0,121000.0,129600.0,253300.0,0.0,244900.0,285400.0,0.0,162600.0,0.0
29,2008-06-30,127300.0,271300.0,209700.0,98800.0,413200.0,218800.0,276800.0,376300.0,221000.0,...,136300.0,120700.0,128300.0,252700.0,0.0,242500.0,282900.0,0.0,162500.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,2014-08-31,121100.0,255600.0,185000.0,110900.0,427400.0,249100.0,240600.0,463300.0,202700.0,...,123200.0,125300.0,135000.0,206800.0,218700.0,230100.0,258500.0,99300.0,153600.0,0.0
104,2014-09-30,121400.0,254400.0,186500.0,111800.0,429400.0,251400.0,240200.0,465200.0,203700.0,...,123000.0,126000.0,135600.0,206600.0,219700.0,230400.0,259400.0,98100.0,154000.0,0.0
105,2014-10-31,121800.0,253600.0,188100.0,112700.0,431500.0,254000.0,239900.0,467100.0,204800.0,...,123200.0,126500.0,136200.0,206900.0,219900.0,231200.0,260700.0,96300.0,154400.0,0.0
106,2014-11-30,122000.0,253300.0,189700.0,113600.0,433500.0,257000.0,239700.0,469600.0,205400.0,...,123700.0,127100.0,136800.0,207200.0,220300.0,232400.0,262600.0,95500.0,154700.0,0.0
107,2014-12-31,121800.0,254900.0,191200.0,114500.0,435300.0,260500.0,239600.0,472200.0,205200.0,...,123900.0,127500.0,138000.0,207800.0,220200.0,233100.0,264500.0,94900.0,154700.0,0.0
108,2015-01-31,121400.0,257200.0,192100.0,115100.0,436600.0,263200.0,239500.0,474100.0,204400.0,...,123700.0,127700.0,139200.0,208600.0,219200.0,233300.0,265800.0,93600.0,154400.0,0.0
109,2015-02-28,120600.0,258000.0,192500.0,114800.0,439500.0,265700.0,237100.0,476600.0,203500.0,...,123500.0,127600.0,140600.0,209100.0,220300.0,232600.0,268400.0,91200.0,153800.0,0.0
110,2015-03-31,120600.0,257300.0,191800.0,114000.0,440000.0,267100.0,239800.0,480300.0,199800.0,...,119400.0,127600.0,141000.0,208900.0,220900.0,231000.0,268800.0,90700.0,152600.0,0.0
111,2015-04-30,120600.0,257200.0,191300.0,114200.0,440700.0,268700.0,236500.0,484400.0,199000.0,...,165300.0,127300.0,142100.0,209300.0,219600.0,230800.0,270400.0,90300.0,153000.0,0.0
112,2015-05-31,121300.0,258100.0,191300.0,114500.0,441800.0,271300.0,236800.0,487600.0,197700.0,...,167700.0,127600.0,143600.0,210500.0,217400.0,230500.0,272900.0,91300.0,152900.0,0.0
113,2015-06-30,122000.0,259500.0,192300.0,114000.0,443200.0,274400.0,237300.0,486600.0,197300.0,...,168200.0,128300.0,144700.0,212000.0,217700.0,230900.0,275000.0,93100.0,154400.0,0.0
114,2015-07-31,121700.0,260500.0,193900.0,113800.0,445500.0,277300.0,237600.0,489400.0,200400.0,...,166100.0,129100.0,145500.0,213700.0,218400.0,230200.0,275900.0,89800.0,155900.0,0.0
115,2015-08-31,122300.0,262000.0,196400.0,113500.0,448400.0,279700.0,237800.0,493100.0,203100.0,...,166600.0,127900.0,149700.0,217400.0,218900.0,232100.0,277000.0,90900.0,154000.0,190800.0
116,2015-09-30,122800.0,262200.0,198600.0,114400.0,447500.0,282200.0,238500.0,497600.0,204400.0,...,171400.0,128900.0,150100.0,219100.0,218500.0,230700.0,279600.0,92300.0,155700.0,191700.0
117,2015-10-31,122200.0,262400.0,199900.0,114000.0,449200.0,284000.0,238000.0,500100.0,204800.0,...,173400.0,129100.0,150600.0,220300.0,218800.0,231100.0,282500.0,93500.0,156700.0,192200.0
118,2015-11-30,122600.0,262700.0,202600.0,114800.0,452300.0,286500.0,237200.0,495600.0,205700.0,...,173900.0,129700.0,151100.0,221200.0,218700.0,231500.0,284600.0,92600.0,156700.0,192400.0
119,2015-12-31,122700.0,264100.0,203600.0,114900.0,454600.0,290100.0,237400.0,497400.0,208600.0,...,174800.0,130300.0,151800.0,222300.0,218000.0,231800.0,286300.0,93900.0,156500.0,192500.0
120,2016-01-31,123100.0,265400.0,204600.0,115200.0,456800.0,292500.0,237700.0,499200.0,210100.0,...,176700.0,130600.0,152600.0,223400.0,218600.0,231800.0,287300.0,96200.0,155800.0,192600.0
121,2016-02-29,123100.0,266200.0,205000.0,115300.0,458500.0,294200.0,237900.0,500500.0,210900.0,...,177800.0,130900.0,153300.0,224300.0,218200.0,231700.0,288600.0,98600.0,155200.0,192600.0
122,2016-03-31,122900.0,267500.0,206100.0,115400.0,462100.0,298500.0,238600.0,500700.0,213100.0,...,176900.0,131500.0,154400.0,225800.0,217500.0,233100.0,294300.0,95700.0,154900.0,193300.0
123,2016-04-30,123300.0,268600.0,207000.0,116500.0,463600.0,302200.0,236200.0,498200.0,210800.0,...,164000.0,132100.0,155400.0,227200.0,216500.0,233800.0,296500.0,96600.0,155600.0,193800.0
124,2016-05-31,122900.0,266500.0,207300.0,114700.0,464200.0,301200.0,238900.0,511700.0,207900.0,...,162900.0,132400.0,156200.0,228100.0,208500.0,234300.0,298700.0,98800.0,155100.0,193600.0
125,2016-06-30,122700.0,266400.0,208000.0,114800.0,466300.0,303600.0,239300.0,516300.0,209300.0,...,172800.0,133500.0,157000.0,229200.0,209300.0,234800.0,301500.0,99500.0,156000.0,194000.0
126,2016-07-31,122300.0,266500.0,208800.0,114400.0,467000.0,305300.0,239700.0,513900.0,210500.0,...,175100.0,134400.0,158100.0,231000.0,211600.0,235400.0,303300.0,99700.0,157400.0,194200.0
127,2016-08-31,122300.0,266800.0,210200.0,115000.0,469500.0,308000.0,240500.0,515100.0,211300.0,...,175300.0,135200.0,159200.0,232300.0,212400.0,235800.0,305800.0,100900.0,158500.0,194400.0
128,2016-09-30,122500.0,265300.0,213200.0,114100.0,476700.0,313700.0,241500.0,523900.0,213100.0,...,163100.0,134300.0,160800.0,236500.0,213800.0,237400.0,311300.0,99100.0,158200.0,193500.0
129,2016-10-31,122800.0,265300.0,214700.0,114900.0,479700.0,316200.0,242300.0,527200.0,213300.0,...,169900.0,135500.0,161300.0,238200.0,0.0,238500.0,313800.0,100200.0,159100.0,193900.0
130,2016-11-30,123200.0,265700.0,216200.0,115300.0,483200.0,318700.0,242900.0,531400.0,214100.0,...,170600.0,136700.0,161800.0,239300.0,0.0,239500.0,316500.0,101600.0,159900.0,194000.0
131,2016-12-31,123800.0,266300.0,217900.0,116100.0,485900.0,320900.0,243100.0,535000.0,214200.0,...,171600.0,137300.0,162400.0,240700.0,0.0,240400.0,317700.0,102000.0,160800.0,194000.0
132,2017-01-31,124600.0,267000.0,219000.0,116700.0,487700.0,322300.0,243300.0,540400.0,214800.0,...,172100.0,138000.0,163100.0,242300.0,0.0,241000.0,318300.0,102400.0,161500.0,194000.0

In [129]:
# Setting the index as the Date column
house_prices.set_index("Date")

,AL,AK,AZ,AR,CA,CO,CT,DC,DE,FL,...,SD,TN,TX,UT,VT,VA,WA,WV,WI,WY
Date,,,,,,,,,,,,,,,,,,,,,
2006-01-31,124000.0,235100.0,259900.0,93200.0,534500.0,222500.0,294300.0,398000.0,225000.0,250600.0,...,130900.0,115000.0,124100.0,193000.0,0.0,261300.0,271100.0,0.0,163800.0,0.0
2006-02-28,124700.0,237100.0,261600.0,93600.0,536100.0,223300.0,294900.0,399600.0,226100.0,253000.0,...,131100.0,115500.0,125100.0,195700.0,0.0,262200.0,274100.0,0.0,164300.0,0.0
2006-03-31,125200.0,238700.0,262900.0,94200.0,537500.0,223400.0,295400.0,400500.0,227200.0,255200.0,...,132000.0,115800.0,127400.0,198300.0,0.0,263000.0,276900.0,0.0,164600.0,0.0
2006-04-30,125600.0,239000.0,263500.0,94500.0,538300.0,223600.0,296000.0,400900.0,228000.0,256600.0,...,132600.0,116300.0,127300.0,201000.0,0.0,263900.0,279800.0,0.0,164700.0,0.0
2006-05-31,126100.0,238500.0,263500.0,94800.0,538300.0,223700.0,296100.0,400900.0,228500.0,257100.0,...,132500.0,117000.0,126600.0,204200.0,0.0,264800.0,282700.0,0.0,164600.0,0.0
2006-06-30,126600.0,237700.0,263000.0,94800.0,537700.0,223500.0,296100.0,399900.0,229200.0,257300.0,...,132200.0,117700.0,127100.0,207800.0,0.0,265700.0,285400.0,0.0,164200.0,0.0
2006-07-31,127200.0,236100.0,262100.0,95100.0,536600.0,223800.0,295800.0,398500.0,230000.0,257000.0,...,132400.0,118300.0,128700.0,211900.0,0.0,266400.0,288100.0,0.0,163700.0,0.0
2006-08-31,127600.0,234700.0,260900.0,95700.0,534800.0,224400.0,295400.0,397800.0,230400.0,256100.0,...,133200.0,118800.0,128400.0,215600.0,0.0,267000.0,290600.0,0.0,163400.0,0.0
2006-09-30,127700.0,235300.0,259400.0,95800.0,532400.0,224700.0,294900.0,397300.0,230600.0,254700.0,...,134100.0,119100.0,128100.0,219600.0,0.0,266800.0,292700.0,0.0,163600.0,0.0
2006-10-31,127800.0,237200.0,257700.0,95300.0,529600.0,225300.0,294700.0,396700.0,231100.0,253300.0,...,135500.0,119600.0,129100.0,223800.0,0.0,266000.0,294400.0,0.0,164100.0,0.0
2006-11-30,128300.0,239000.0,256100.0,95400.0,527000.0,226300.0,294300.0,396100.0,232000.0,251600.0,...,137100.0,120400.0,131000.0,227300.0,0.0,265400.0,296200.0,0.0,164300.0,0.0
2006-12-31,129100.0,243500.0,254300.0,95900.0,523900.0,227100.0,293800.0,396000.0,232600.0,249400.0,...,137100.0,121000.0,132300.0,230600.0,0.0,265400.0,297600.0,0.0,164400.0,0.0
2007-01-31,129400.0,249500.0,252300.0,96300.0,521000.0,226900.0,293500.0,396300.0,232800.0,247000.0,...,136400.0,121200.0,133600.0,234900.0,0.0,265400.0,298500.0,0.0,164700.0,0.0
2007-02-28,129300.0,255300.0,250300.0,96600.0,518700.0,226300.0,293600.0,397000.0,232600.0,244900.0,...,136900.0,121500.0,132800.0,239300.0,0.0,265300.0,299200.0,0.0,164700.0,0.0
2007-03-31,129300.0,258800.0,248400.0,97100.0,516700.0,226100.0,293800.0,398200.0,232900.0,242700.0,...,138400.0,121900.0,131600.0,243400.0,0.0,265300.0,300100.0,0.0,165000.0,0.0
2007-04-30,129300.0,261500.0,246700.0,97500.0,513900.0,226000.0,293900.0,398600.0,233200.0,239900.0,...,139200.0,122200.0,132500.0,247000.0,0.0,265300.0,300700.0,0.0,165800.0,0.0
2007-05-31,129200.0,261900.0,245000.0,97700.0,510500.0,226200.0,293400.0,397600.0,233100.0,237000.0,...,140200.0,122300.0,134200.0,249300.0,0.0,265200.0,301000.0,0.0,166400.0,0.0
2007-06-30,129300.0,262700.0,243300.0,97900.0,506100.0,226900.0,292400.0,396500.0,232500.0,234200.0,...,140500.0,122400.0,134600.0,251000.0,0.0,263600.0,300900.0,0.0,166000.0,0.0
2007-07-31,129700.0,264000.0,241700.0,98300.0,501200.0,227500.0,291400.0,395900.0,232300.0,231300.0,...,139100.0,122400.0,134700.0,252500.0,0.0,260200.0,300800.0,0.0,165400.0,0.0
2007-08-31,129900.0,265600.0,240200.0,98500.0,496200.0,226900.0,290500.0,395600.0,232000.0,228100.0,...,137600.0,122600.0,135000.0,254100.0,0.0,256000.0,300500.0,0.0,165000.0,0.0
2007-09-30,130000.0,265700.0,238600.0,98700.0,490900.0,226900.0,289500.0,395200.0,231300.0,224900.0,...,137100.0,122800.0,135500.0,255500.0,0.0,255400.0,299600.0,0.0,164600.0,0.0
2007-10-31,130000.0,265500.0,236900.0,99300.0,485400.0,227100.0,288400.0,393800.0,230500.0,221800.0,...,135900.0,122800.0,135100.0,256700.0,0.0,257500.0,298200.0,0.0,164400.0,0.0
2007-11-30,129500.0,264700.0,234900.0,99900.0,479300.0,226700.0,287500.0,391300.0,229800.0,218700.0,...,134900.0,122600.0,134500.0,258000.0,0.0,258000.0,296700.0,0.0,164100.0,0.0
2007-12-31,128400.0,265900.0,232200.0,99600.0,471900.0,224800.0,286100.0,388600.0,228900.0,215200.0,...,135000.0,122300.0,135000.0,259800.0,0.0,255800.0,294900.0,0.0,163900.0,0.0
2008-01-31,127400.0,267800.0,228500.0,99300.0,463300.0,222300.0,284300.0,386200.0,227900.0,211100.0,...,135300.0,121900.0,135400.0,261300.0,0.0,253900.0,292900.0,0.0,163100.0,0.0
2008-02-29,126800.0,268200.0,224500.0,99200.0,454100.0,220000.0,282500.0,383700.0,226800.0,206600.0,...,135600.0,121600.0,134200.0,259900.0,0.0,251800.0,291000.0,0.0,162600.0,0.0
2008-03-31,126500.0,267200.0,220500.0,99400.0,443900.0,219100.0,280900.0,381300.0,225400.0,202100.0,...,135900.0,121600.0,132300.0,256300.0,0.0,249600.0,289100.0,0.0,162600.0,0.0
2008-04-30,126500.0,268400.0,216700.0,99400.0,433300.0,218600.0,279500.0,379600.0,223800.0,197800.0,...,136200.0,121300.0,131100.0,254000.0,0.0,247300.0,287400.0,0.0,162900.0,0.0
2008-05-31,126700.0,269900.0,213300.0,99100.0,423000.0,218600.0,278100.0,378200.0,222300.0,193600.0,...,136200.0,121000.0,129600.0,253300.0,0.0,244900.0,285400.0,0.0,162600.0,0.0
2008-06-30,127300.0,271300.0,209700.0,98800.0,413200.0,218800.0,276800.0,376300.0,221000.0,189500.0,...,136300.0,120700.0,128300.0,252700.0,0.0,242500.0,282900.0,0.0,162500.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-08-31,121100.0,255600.0,185000.0,110900.0,427400.0,249100.0,240600.0,463300.0,202700.0,164700.0,...,123200.0,125300.0,135000.0,206800.0,218700.0,230100.0,258500.0,99300.0,153600.0,0.0
2014-09-30,121400.0,254400.0,186500.0,111800.0,429400.0,251400.0,240200.0,465200.0,203700.0,165700.0,...,123000.0,126000.0,135600.0,206600.0,219700.0,230400.0,259400.0,98100.0,154000.0,0.0
2014-10-31,121800.0,253600.0,188100.0,112700.0,431500.0,254000.0,239900.0,467100.0,204800.0,166400.0,...,123200.0,126500.0,136200.0,206900.0,219900.0,231200.0,260700.0,96300.0,154400.0,0.0
2014-11-30,122000.0,253300.0,189700.0,113600.0,433500.0,257000.0,239700.0,469600.0,205400.0,167400.0,...,123700.0,127100.0,136800.0,207200.0,220300.0,232400.0,262600.0,95500.0,154700.0,0.0
2014-12-31,121800.0,254900.0,191200.0,114500.0,435300.0,260500.0,239600.0,472200.0,205200.0,168600.0,...,123900.0,127500.0,138000.0,207800.0,220200.0,233100.0,264500.0,94900.0,154700.0,0.0
2015-01-31,121400.0,257200.0,192100.0,115100.0,436600.0,263200.0,239500.0,474100.0,204400.0,169400.0,...,123700.0,127700.0,139200.0,208600.0,219200.0,233300.0,265800.0,93600.0,154400.0,0.0
2015-02-28,120600.0,258000.0,192500.0,114800.0,439500.0,265700.0,237100.0,476600.0,203500.0,169700.0,...,123500.0,127600.0,140600.0,209100.0,220300.0,232600.0,268400.0,91200.0,153800.0,0.0
2015-03-31,120600.0,257300.0,191800.0,114000.0,440000.0,267100.0,239800.0,480300.0,199800.0,170500.0,...,119400.0,127600.0,141000.0,208900.0,220900.0,231000.0,268800.0,90700.0,152600.0,0.0
2015-04-30,120600.0,257200.0,191300.0,114200.0,440700.0,268700.0,236500.0,484400.0,199000.0,171100.0,...,165300.0,127300.0,142100.0,209300.0,219600.0,230800.0,270400.0,90300.0,153000.0,0.0
2015-05-31,121300.0,258100.0,191300.0,114500.0,441800.0,271300.0,236800.0,487600.0,197700.0,171800.0,...,167700.0,127600.0,143600.0,210500.0,217400.0,230500.0,272900.0,91300.0,152900.0,0.0
2015-06-30,122000.0,259500.0,192300.0,114000.0,443200.0,274400.0,237300.0,486600.0,197300.0,172800.0,...,168200.0,128300.0,144700.0,212000.0,217700.0,230900.0,275000.0,93100.0,154400.0,0.0
2015-07-31,121700.0,260500.0,193900.0,113800.0,445500.0,277300.0,237600.0,489400.0,200400.0,174100.0,...,166100.0,129100.0,145500.0,213700.0,218400.0,230200.0,275900.0,89800.0,155900.0,0.0
2015-08-31,122300.0,262000.0,196400.0,113500.0,448400.0,279700.0,237800.0,493100.0,203100.0,176600.0,...,166600.0,127900.0,149700.0,217400.0,218900.0,232100.0,277000.0,90900.0,154000.0,190800.0
2015-09-30,122800.0,262200.0,198600.0,114400.0,447500.0,282200.0,238500.0,497600.0,204400.0,178300.0,...,171400.0,128900.0,150100.0,219100.0,218500.0,230700.0,279600.0,92300.0,155700.0,191700.0
2015-10-31,122200.0,262400.0,199900.0,114000.0,449200.0,284000.0,238000.0,500100.0,204800.0,179700.0,...,173400.0,129100.0,150600.0,220300.0,218800.0,231100.0,282500.0,93500.0,156700.0,192200.0
2015-11-30,122600.0,262700.0,202600.0,114800.0,452300.0,286500.0,237200.0,495600.0,205700.0,180800.0,...,173900.0,129700.0,151100.0,221200.0,218700.0,231500.0,284600.0,92600.0,156700.0,192400.0
2015-12-31,122700.0,264100.0,203600.0,114900.0,454600.0,290100.0,237400.0,497400.0,208600.0,182100.0,...,174800.0,130300.0,151800.0,222300.0,218000.0,231800.0,286300.0,93900.0,156500.0,192500.0
2016-01-31,123100.0,265400.0,204600.0,115200.0,456800.0,292500.0,237700.0,499200.0,210100.0,183900.0,...,176700.0,130600.0,152600.0,223400.0,218600.0,231800.0,287300.0,96200.0,155800.0,192600.0
2016-02-29,123100.0,266200.0,205000.0,115300.0,458500.0,294200.0,237900.0,500500.0,210900.0,185000.0,...,177800.0,130900.0,153300.0,224300.0,218200.0,231700.0,288600.0,98600.0,155200.0,192600.0
2016-03-31,122900.0,267500.0,206100.0,115400.0,462100.0,298500.0,238600.0,500700.0,213100.0,186100.0,...,176900.0,131500.0,154400.0,225800.0,217500.0,233100.0,294300.0,95700.0,154900.0,193300.0
2016-04-30,123300.0,268600.0,207000.0,116500.0,463600.0,302200.0,236200.0,498200.0,210800.0,187200.0,...,164000.0,132100.0,155400.0,227200.0,216500.0,233800.0,296500.0,96600.0,155600.0,193800.0
2016-05-31,122900.0,266500.0,207300.0,114700.0,464200.0,301200.0,238900.0,511700.0,207900.0,188000.0,...,162900.0,132400.0,156200.0,228100.0,208500.0,234300.0,298700.0,98800.0,155100.0,193600.0
2016-06-30,122700.0,266400.0,208000.0,114800.0,466300.0,303600.0,239300.0,516300.0,209300.0,189500.0,...,172800.0,133500.0,157000.0,229200.0,209300.0,234800.0,301500.0,99500.0,156000.0,194000.0
2016-07-31,122300.0,266500.0,208800.0,114400.0,467000.0,305300.0,239700.0,513900.0,210500.0,191100.0,...,175100.0,134400.0,158100.0,231000.0,211600.0,235400.0,303300.0,99700.0,157400.0,194200.0
2016-08-31,122300.0,266800.0,210200.0,115000.0,469500.0,308000.0,240500.0,515100.0,211300.0,192600.0,...,175300.0,135200.0,159200.0,232300.0,212400.0,235800.0,305800.0,100900.0,158500.0,194400.0
2016-09-30,122500.0,265300.0,213200.0,114100.0,476700.0,313700.0,241500.0,523900.0,213100.0,196200.0,...,163100.0,134300.0,160800.0,236500.0,213800.0,237400.0,311300.0,99100.0,158200.0,193500.0
2016-10-31,122800.0,265300.0,214700.0,114900.0,479700.0,316200.0,242300.0,527200.0,213300.0,198000.0,...,169900.0,135500.0,161300.0,238200.0,0.0,238500.0,313800.0,100200.0,159100.0,193900.0
2016-11-30,123200.0,265700.0,216200.0,115300.0,483200.0,318700.0,242900.0,531400.0,214100.0,200100.0,...,170600.0,136700.0,161800.0,239300.0,0.0,239500.0,316500.0,101600.0,159900.0,194000.0
2016-12-31,123800.0,266300.0,217900.0,116100.0,485900.0,320900.0,243100.0,535000.0,214200.0,201800.0,...,171600.0,137300.0,162400.0,240700.0,0.0,240400.0,317700.0,102000.0,160800.0,194000.0
2017-01-31,124600.0,267000.0,219000.0,116700.0,487700.0,322300.0,243300.0,540400.0,214800.0,203200.0,...,172100.0,138000.0,163100.0,242300.0,0.0,241000.0,318300.0,102400.0,161500.0,194000.0

In [130]:
#house_prices=house_prices.T

In [131]:
# Confirming the changes
house_prices

,Date,AL,AK,AZ,AR,CA,CO,CT,DC,DE,...,SD,TN,TX,UT,VT,VA,WA,WV,WI,WY
0,2006-01-31,124000.0,235100.0,259900.0,93200.0,534500.0,222500.0,294300.0,398000.0,225000.0,...,130900.0,115000.0,124100.0,193000.0,0.0,261300.0,271100.0,0.0,163800.0,0.0
1,2006-02-28,124700.0,237100.0,261600.0,93600.0,536100.0,223300.0,294900.0,399600.0,226100.0,...,131100.0,115500.0,125100.0,195700.0,0.0,262200.0,274100.0,0.0,164300.0,0.0
2,2006-03-31,125200.0,238700.0,262900.0,94200.0,537500.0,223400.0,295400.0,400500.0,227200.0,...,132000.0,115800.0,127400.0,198300.0,0.0,263000.0,276900.0,0.0,164600.0,0.0
3,2006-04-30,125600.0,239000.0,263500.0,94500.0,538300.0,223600.0,296000.0,400900.0,228000.0,...,132600.0,116300.0,127300.0,201000.0,0.0,263900.0,279800.0,0.0,164700.0,0.0
4,2006-05-31,126100.0,238500.0,263500.0,94800.0,538300.0,223700.0,296100.0,400900.0,228500.0,...,132500.0,117000.0,126600.0,204200.0,0.0,264800.0,282700.0,0.0,164600.0,0.0
5,2006-06-30,126600.0,237700.0,263000.0,94800.0,537700.0,223500.0,296100.0,399900.0,229200.0,...,132200.0,117700.0,127100.0,207800.0,0.0,265700.0,285400.0,0.0,164200.0,0.0
6,2006-07-31,127200.0,236100.0,262100.0,95100.0,536600.0,223800.0,295800.0,398500.0,230000.0,...,132400.0,118300.0,128700.0,211900.0,0.0,266400.0,288100.0,0.0,163700.0,0.0
7,2006-08-31,127600.0,234700.0,260900.0,95700.0,534800.0,224400.0,295400.0,397800.0,230400.0,...,133200.0,118800.0,128400.0,215600.0,0.0,267000.0,290600.0,0.0,163400.0,0.0
8,2006-09-30,127700.0,235300.0,259400.0,95800.0,532400.0,224700.0,294900.0,397300.0,230600.0,...,134100.0,119100.0,128100.0,219600.0,0.0,266800.0,292700.0,0.0,163600.0,0.0
9,2006-10-31,127800.0,237200.0,257700.0,95300.0,529600.0,225300.0,294700.0,396700.0,231100.0,...,135500.0,119600.0,129100.0,223800.0,0.0,266000.0,294400.0,0.0,164100.0,0.0
10,2006-11-30,128300.0,239000.0,256100.0,95400.0,527000.0,226300.0,294300.0,396100.0,232000.0,...,137100.0,120400.0,131000.0,227300.0,0.0,265400.0,296200.0,0.0,164300.0,0.0
11,2006-12-31,129100.0,243500.0,254300.0,95900.0,523900.0,227100.0,293800.0,396000.0,232600.0,...,137100.0,121000.0,132300.0,230600.0,0.0,265400.0,297600.0,0.0,164400.0,0.0
12,2007-01-31,129400.0,249500.0,252300.0,96300.0,521000.0,226900.0,293500.0,396300.0,232800.0,...,136400.0,121200.0,133600.0,234900.0,0.0,265400.0,298500.0,0.0,164700.0,0.0
13,2007-02-28,129300.0,255300.0,250300.0,96600.0,518700.0,226300.0,293600.0,397000.0,232600.0,...,136900.0,121500.0,132800.0,239300.0,0.0,265300.0,299200.0,0.0,164700.0,0.0
14,2007-03-31,129300.0,258800.0,248400.0,97100.0,516700.0,226100.0,293800.0,398200.0,232900.0,...,138400.0,121900.0,131600.0,243400.0,0.0,265300.0,300100.0,0.0,165000.0,0.0
15,2007-04-30,129300.0,261500.0,246700.0,97500.0,513900.0,226000.0,293900.0,398600.0,233200.0,...,139200.0,122200.0,132500.0,247000.0,0.0,265300.0,300700.0,0.0,165800.0,0.0
16,2007-05-31,129200.0,261900.0,245000.0,97700.0,510500.0,226200.0,293400.0,397600.0,233100.0,...,140200.0,122300.0,134200.0,249300.0,0.0,265200.0,301000.0,0.0,166400.0,0.0
17,2007-06-30,129300.0,262700.0,243300.0,97900.0,506100.0,226900.0,292400.0,396500.0,232500.0,...,140500.0,122400.0,134600.0,251000.0,0.0,263600.0,300900.0,0.0,166000.0,0.0
18,2007-07-31,129700.0,264000.0,241700.0,98300.0,501200.0,227500.0,291400.0,395900.0,232300.0,...,139100.0,122400.0,134700.0,252500.0,0.0,260200.0,300800.0,0.0,165400.0,0.0
19,2007-08-31,129900.0,265600.0,240200.0,98500.0,496200.0,226900.0,290500.0,395600.0,232000.0,...,137600.0,122600.0,135000.0,254100.0,0.0,256000.0,300500.0,0.0,165000.0,0.0
20,2007-09-30,130000.0,265700.0,238600.0,98700.0,490900.0,226900.0,289500.0,395200.0,231300.0,...,137100.0,122800.0,135500.0,255500.0,0.0,255400.0,299600.0,0.0,164600.0,0.0
21,2007-10-31,130000.0,265500.0,236900.0,99300.0,485400.0,227100.0,288400.0,393800.0,230500.0,...,135900.0,122800.0,135100.0,256700.0,0.0,257500.0,298200.0,0.0,164400.0,0.0
22,2007-11-30,129500.0,264700.0,234900.0,99900.0,479300.0,226700.0,287500.0,391300.0,229800.0,...,134900.0,122600.0,134500.0,258000.0,0.0,258000.0,296700.0,0.0,164100.0,0.0
23,2007-12-31,128400.0,265900.0,232200.0,99600.0,471900.0,224800.0,286100.0,388600.0,228900.0,...,135000.0,122300.0,135000.0,259800.0,0.0,255800.0,294900.0,0.0,163900.0,0.0
24,2008-01-31,127400.0,267800.0,228500.0,99300.0,463300.0,222300.0,284300.0,386200.0,227900.0,...,135300.0,121900.0,135400.0,261300.0,0.0,253900.0,292900.0,0.0,163100.0,0.0
25,2008-02-29,126800.0,268200.0,224500.0,99200.0,454100.0,220000.0,282500.0,383700.0,226800.0,...,135600.0,121600.0,134200.0,259900.0,0.0,251800.0,291000.0,0.0,162600.0,0.0
26,2008-03-31,126500.0,267200.0,220500.0,99400.0,443900.0,219100.0,280900.0,381300.0,225400.0,...,135900.0,121600.0,132300.0,256300.0,0.0,249600.0,289100.0,0.0,162600.0,0.0
27,2008-04-30,126500.0,268400.0,216700.0,99400.0,433300.0,218600.0,279500.0,379600.0,223800.0,...,136200.0,121300.0,131100.0,254000.0,0.0,247300.0,287400.0,0.0,162900.0,0.0
28,2008-05-31,126700.0,269900.0,213300.0,99100.0,423000.0,218600.0,278100.0,378200.0,222300.0,...,136200.0,121000.0,129600.0,253300.0,0.0,244900.0,285400.0,0.0,162600.0,0.0
29,2008-06-30,127300.0,271300.0,209700.0,98800.0,413200.0,218800.0,276800.0,376300.0,221000.0,...,136300.0,120700.0,128300.0,252700.0,0.0,242500.0,282900.0,0.0,162500.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,2014-08-31,121100.0,255600.0,185000.0,110900.0,427400.0,249100.0,240600.0,463300.0,202700.0,...,123200.0,125300.0,135000.0,206800.0,218700.0,230100.0,258500.0,99300.0,153600.0,0.0
104,2014-09-30,121400.0,254400.0,186500.0,111800.0,429400.0,251400.0,240200.0,465200.0,203700.0,...,123000.0,126000.0,135600.0,206600.0,219700.0,230400.0,259400.0,98100.0,154000.0,0.0
105,2014-10-31,121800.0,253600.0,188100.0,112700.0,431500.0,254000.0,239900.0,467100.0,204800.0,...,123200.0,126500.0,136200.0,206900.0,219900.0,231200.0,260700.0,96300.0,154400.0,0.0
106,2014-11-30,122000.0,253300.0,189700.0,113600.0,433500.0,257000.0,239700.0,469600.0,205400.0,...,123700.0,127100.0,136800.0,207200.0,220300.0,232400.0,262600.0,95500.0,154700.0,0.0
107,2014-12-31,121800.0,254900.0,191200.0,114500.0,435300.0,260500.0,239600.0,472200.0,205200.0,...,123900.0,127500.0,138000.0,207800.0,220200.0,233100.0,264500.0,94900.0,154700.0,0.0
108,2015-01-31,121400.0,257200.0,192100.0,115100.0,436600.0,263200.0,239500.0,474100.0,204400.0,...,123700.0,127700.0,139200.0,208600.0,219200.0,233300.0,265800.0,93600.0,154400.0,0.0
109,2015-02-28,120600.0,258000.0,192500.0,114800.0,439500.0,265700.0,237100.0,476600.0,203500.0,...,123500.0,127600.0,140600.0,209100.0,220300.0,232600.0,268400.0,91200.0,153800.0,0.0
110,2015-03-31,120600.0,257300.0,191800.0,114000.0,440000.0,267100.0,239800.0,480300.0,199800.0,...,119400.0,127600.0,141000.0,208900.0,220900.0,231000.0,268800.0,90700.0,152600.0,0.0
111,2015-04-30,120600.0,257200.0,191300.0,114200.0,440700.0,268700.0,236500.0,484400.0,199000.0,...,165300.0,127300.0,142100.0,209300.0,219600.0,230800.0,270400.0,90300.0,153000.0,0.0
112,2015-05-31,121300.0,258100.0,191300.0,114500.0,441800.0,271300.0,236800.0,487600.0,197700.0,...,167700.0,127600.0,143600.0,210500.0,217400.0,230500.0,272900.0,91300.0,152900.0,0.0
113,2015-06-30,122000.0,259500.0,192300.0,114000.0,443200.0,274400.0,237300.0,486600.0,197300.0,...,168200.0,128300.0,144700.0,212000.0,217700.0,230900.0,275000.0,93100.0,154400.0,0.0
114,2015-07-31,121700.0,260500.0,193900.0,113800.0,445500.0,277300.0,237600.0,489400.0,200400.0,...,166100.0,129100.0,145500.0,213700.0,218400.0,230200.0,275900.0,89800.0,155900.0,0.0
115,2015-08-31,122300.0,262000.0,196400.0,113500.0,448400.0,279700.0,237800.0,493100.0,203100.0,...,166600.0,127900.0,149700.0,217400.0,218900.0,232100.0,277000.0,90900.0,154000.0,190800.0
116,2015-09-30,122800.0,262200.0,198600.0,114400.0,447500.0,282200.0,238500.0,497600.0,204400.0,...,171400.0,128900.0,150100.0,219100.0,218500.0,230700.0,279600.0,92300.0,155700.0,191700.0
117,2015-10-31,122200.0,262400.0,199900.0,114000.0,449200.0,284000.0,238000.0,500100.0,204800.0,...,173400.0,129100.0,150600.0,220300.0,218800.0,231100.0,282500.0,93500.0,156700.0,192200.0
118,2015-11-30,122600.0,262700.0,202600.0,114800.0,452300.0,286500.0,237200.0,495600.0,205700.0,...,173900.0,129700.0,151100.0,221200.0,218700.0,231500.0,284600.0,92600.0,156700.0,192400.0
119,2015-12-31,122700.0,264100.0,203600.0,114900.0,454600.0,290100.0,237400.0,497400.0,208600.0,...,174800.0,130300.0,151800.0,222300.0,218000.0,231800.0,286300.0,93900.0,156500.0,192500.0
120,2016-01-31,123100.0,265400.0,204600.0,115200.0,456800.0,292500.0,237700.0,499200.0,210100.0,...,176700.0,130600.0,152600.0,223400.0,218600.0,231800.0,287300.0,96200.0,155800.0,192600.0
121,2016-02-29,123100.0,266200.0,205000.0,115300.0,458500.0,294200.0,237900.0,500500.0,210900.0,...,177800.0,130900.0,153300.0,224300.0,218200.0,231700.0,288600.0,98600.0,155200.0,192600.0
122,2016-03-31,122900.0,267500.0,206100.0,115400.0,462100.0,298500.0,238600.0,500700.0,213100.0,...,176900.0,131500.0,154400.0,225800.0,217500.0,233100.0,294300.0,95700.0,154900.0,193300.0
123,2016-04-30,123300.0,268600.0,207000.0,116500.0,463600.0,302200.0,236200.0,498200.0,210800.0,...,164000.0,132100.0,155400.0,227200.0,216500.0,233800.0,296500.0,96600.0,155600.0,193800.0
124,2016-05-31,122900.0,266500.0,207300.0,114700.0,464200.0,301200.0,238900.0,511700.0,207900.0,...,162900.0,132400.0,156200.0,228100.0,208500.0,234300.0,298700.0,98800.0,155100.0,193600.0
125,2016-06-30,122700.0,266400.0,208000.0,114800.0,466300.0,303600.0,239300.0,516300.0,209300.0,...,172800.0,133500.0,157000.0,229200.0,209300.0,234800.0,301500.0,99500.0,156000.0,194000.0
126,2016-07-31,122300.0,266500.0,208800.0,114400.0,467000.0,305300.0,239700.0,513900.0,210500.0,...,175100.0,134400.0,158100.0,231000.0,211600.0,235400.0,303300.0,99700.0,157400.0,194200.0
127,2016-08-31,122300.0,266800.0,210200.0,115000.0,469500.0,308000.0,240500.0,515100.0,211300.0,...,175300.0,135200.0,159200.0,232300.0,212400.0,235800.0,305800.0,100900.0,158500.0,194400.0
128,2016-09-30,122500.0,265300.0,213200.0,114100.0,476700.0,313700.0,241500.0,523900.0,213100.0,...,163100.0,134300.0,160800.0,236500.0,213800.0,237400.0,311300.0,99100.0,158200.0,193500.0
129,2016-10-31,122800.0,265300.0,214700.0,114900.0,479700.0,316200.0,242300.0,527200.0,213300.0,...,169900.0,135500.0,161300.0,238200.0,0.0,238500.0,313800.0,100200.0,159100.0,193900.0
130,2016-11-30,123200.0,265700.0,216200.0,115300.0,483200.0,318700.0,242900.0,531400.0,214100.0,...,170600.0,136700.0,161800.0,239300.0,0.0,239500.0,316500.0,101600.0,159900.0,194000.0
131,2016-12-31,123800.0,266300.0,217900.0,116100.0,485900.0,320900.0,243100.0,535000.0,214200.0,...,171600.0,137300.0,162400.0,240700.0,0.0,240400.0,317700.0,102000.0,160800.0,194000.0
132,2017-01-31,124600.0,267000.0,219000.0,116700.0,487700.0,322300.0,243300.0,540400.0,214800.0,...,172100.0,138000.0,163100.0,242300.0,0.0,241000.0,318300.0,102400.0,161500.0,194000.0

In [132]:
# Using the house_prices data frame, create a plot in jupyter notebook with iplot, setting Data as the x axis,
# and filling the areas with unique individual colours.  Then using vspan section off part off the graphpg to indicate the 
# recession period. x0 is the start and x1 is the en of the recession, using rgb to colour the area grey opacity 
# to control tha shade.  I then set the Titles for the x and y axis and the main grph title

In [133]:
house_prices.iplot(x='Date', fill=True, 
vspan={'x0':'2007-12-01','x1':'2009-06-30','color':'rgba(30,30,30,0.3)','fill':True,'opacity':.4},
xTitle='Date',yTitle='House Price ($)',title='House Prices')